### ISSUE TITLE
Warning: DebugPanel(...): React component classes must extend React.Component.

### ISSUE THREAD

**Issue by billyjanitsch** [gaearon/redux-devtools#100]
The latest version of React (v0.14-rc1) throws a warning for devtools components (DebugPanel, LogMonitor, LogMonitorEntry) because they [don't extend `React.Component`](https://github.com/gaearon/redux-devtools/blob/master/src/react/DebugPanel.js#L31).

**Comment by tonyalaribe** [comment]
Yeah... I'm equally experiencing this.

**Comment by gaearon** [comment]
Fixed by #103.

**Comment by gaearon** [comment]
Out in 2.1.1.
