### ISSUE TITLE
Add warning for non-deterministic reducers in documentation

### ISSUE THREAD

**Issue by OAGr** [gaearon/redux-devtools#102]
I had a reducer that looked like this:
```javascript
export default function items(state = initialMetrics, action) {
  switch (action.type) {
  case 'ADD_METRIC':
    let newItem = Object.assign({}, {id: uuid.v4(), location: action.location})
    return [...state, newItem]
}
```

The key part here is ```uuid.v4()```, which produces a random number for the item ID.  This caused very strange behavior in Redux with the Devtools.  It seems like Redux Devtools re-renders the props for each previous action with each new action, so this means that for each new element I created (call this variable ```ni```), each additional action would trigger ```ni``` re-creations of new IDs, and change the DOM each time.  This is definitely not what I expected and took a while to debug.

I'm curious if my understanding of devtools is correct and what possible solutions would be.
1.  Simply warn people to have deterministic actions/reducers in the docs (I realize that random functions are not 'pure', but I still found this surprising)
2.  Find some way to cache input/output behaviors and not run the stores each time.  

I'm also curious what I can do about this.  Some ideas:
1.  Use a deterministic (and not based on time) ID system.
2.  Create the random ID in the React component before passing it to the action.
3. Figure out something else.

**Comment by OAGr** [comment]
Realized that this seems to be the same issue as this.  Closing.

https://github.com/gaearon/redux-devtools/issues/32

**Comment by gaearon** [comment]
Let's keep it open for docs.

**Comment by gaearon** [comment]
Fixed in https://github.com/gaearon/redux-devtools/commit/28c20623901d37b2475139c7d1143eb2278709b8.

**Comment by OAGr** [comment]
Awesome, thanks!
