### ISSUE TITLE
devTools prevents immutable checks from working.

### ISSUE THREAD

**Issue by gregthebusker** [gaearon/redux-devtools#105]
So I think the issues comes down to recomputeStates in devTools.js  Basically because recomputeStates provides a completely new state any check to see if the state has changed for object and arrays will falsely return true.  Let me give you an example.

```sh
var initialState = {
  mySet: new Set(),
};

var anyAction = (o) => {
  return {
    type: 'something',
  }
};

var reducer = (state=initialState, action) => {
  switch(action.type) {
    case 'something':
      return {
        ...state,
      }
  }
};

// Somewhere in some react component
componentWillReceiveProps(nextProps) {
  if (nextProps.mySet != this.props.mySet) {
    this.props.dispatch(anyAction());
  }
}
```

Because recomputeStates, builds a new state object, nextProps.mySet will change with every action, thus dispatching anyAction will cause an infinite loop.

**Comment by bizangles** [comment]
I have been experiencing this issue, but with the componentDidUpdate method. I assume it's the same problem, though.

**Comment by gaearon** [comment]
Please see part 1 of https://github.com/gaearon/redux-devtools/issues/88#issuecomment-135107470.
