### ISSUE TITLE
allow resizing/collapsing

### ISSUE THREAD

**Issue by pdeva** [gaearon/redux-devtools#109]
extremely tough to use cause sometimes its over the content/button that i need to use.
should allow resizing/collapsing.

**Comment by pdeva** [comment]
For example, this screenshot explains this issue:
http://screencast.com/t/NTIDCeD1IV

**Comment by AsaAyers** [comment]
You can hide it, but I'm not aware of a way to resize it:

> * Toggle visibility with Ctrl+H
> * To hide the devtools on load, set visibleOnLoad to false, e.g.: `<DevTools store={store} monitor={LogMonitor} visibleOnLoad={false} />`

**Comment by pdeva** [comment]
the shortcut is not documented anywhere.

also Ctrl+H is shortcut for 'History' in chrome. many times i trigger that when focus is not entirely inside window. a different shortcut would be much better.

**Comment by gaearon** [comment]
>the shortcut is not documented anywhere.

Why don't you make a PR then?

**Comment by gaearon** [comment]
>extremely tough to use cause sometimes its over the content/button that i need to use.
>should allow resizing/collapsing.

You might be interested in giving feedback to https://github.com/gaearon/redux-devtools/pull/107.

**Comment by gaearon** [comment]
>also Ctrl+H is shortcut for 'History' in chrome. many times i trigger that when focus is not entirely inside window. a different shortcut would be much better.

File an issue, suggest another shortcut, make a PR. This is open source. If you can make it better, make it better.

**Comment by billyjanitsch** [comment]
> the shortcut is not documented anywhere.

Actually, it's already documented in the [Readme](https://github.com/gaearon/redux-devtools#features), which is what @AsaAyers was quoting.

The code responsible for defining Ctrl+H is [here](https://github.com/gaearon/redux-devtools/blob/master/src/react/LogMonitor.js#L128), if that helps.

Incidentally, even if you're not comfortable submitting a PR and don't have a specific improvement in mind, a little more politeness (e.g. "Is this shortcut documented? I don't see it") will make someone a lot more inclined to fix it for you. :) If you're going to make terse complaints, at least make sure not to be incorrect.

**Comment by nicolabortignon** [comment]
I'm happy to implement this PR if everyone are ok with it:
- adding a close/open toggle.
- adding resize capabilities
- leave CTRL+H as it is (doesn't conflict if the target is the page)

Thoughts ?

**Comment by gaearon** [comment]
https://github.com/gaearon/redux-devtools/pull/107 addresses this partly.
It's on hold until `LogMonitor` is extracted into a separate project.

**Comment by gaearon** [comment]
Let's track this in #132 which will include an official docking solution.
