### ISSUE TITLE
Address browserify in README

### ISSUE THREAD

**Issue by burtyish** [gaearon/redux-devtools#115]
As a browserify user, the section of the README warning users to "Make sure to only apply devTools() in development!" left me confused. I'm not sure how I'd do that in browserify (and grunt) for a browser-only app and I failed to find an example.
I've looked at [envify](https://github.com/hughsk/envify) but it looks like it's for an app running on a server (based on env. variables). 

Thanks!

**Comment by gaearon** [comment]
Envify is exactly for this; it's not related to running on server. We assume the user is familiar with envifying because, if you use React, you *have to* envify anyway—otherwise you're using development version of React which is slow.

I'm happy to see a PR addressing this in README.

**Comment by burtyish** [comment]
> if you use React, you *have* to envify anyway

Not necessarily. I've been using the following format in my build script: `NODE_ENV=production gulp build` (not exactly that, since I use grunt) to set the `NODE_ENV` env var. Of course, that way I wasn't benefiting from dead code removal via uglify.

Anyway, your comment pointed me in the right direction, so thanks again!
