### ISSUE TITLE
Import and Export action logs

### ISSUE THREAD

**Issue by pabloalonsos** [gaearon/redux-devtools#117]
I was looking at #49, #62 and the source code and it seems like there is already an ongoing idea of implementing some sort of import/export action-log feature but I can't seem to find a clear place where this lives.

I've put together a small addition to the code that would allow us to do so. Maybe there is already something in place to achieve this, or maybe this is not where/how this should be set up, but I thought it was worth sharing. This feature (or something similar) would be awesome to use for QA purposes among other things. If you guys think this makes sense I could create a PR, else, any constructive criticism would be more than welcome!

https://github.com/pabloalonsos/redux-devtools/commit/496baa9206fb59799b58272bf0465cf8d6f216e5

**Comment by gaearon** [comment]
Why did you close this?

**Comment by gaearon** [comment]
A PR is welcome, would you mind creating one?
