### ISSUE TITLE
Persisting state during reload

### ISSUE THREAD

**Issue by sbichenko** [gaearon/redux-devtools#121]
Consider an example Counter app, that can `decrement` and `increment` its value by 1 and display the resulting value. Every time value is changed, it is saved to localStorage. On reload, the app checks whether there is a saved state, and, if so, uses it as initial state.

![image](https://cloud.githubusercontent.com/assets/3719275/9981002/a52b8bb4-5fb7-11e5-91ce-63ff2c01ca87.png)

I've tried implementing it in two ways, and both of them don't work with Redux DevTools.

**First,** I tried using a reducer to fetch state, so that my React component dispatched a `LOAD` action on `didComponentMount`. The reducer for that action then fetched the data from `window.localstorage`. The reducer thus became impure, which seems to be explicitly forbidden by the API. Devtools, when reloading a session (with `?debug_session=123` in the URL) got the initial state right,but since it re-runs the whole sequence of actions on each increment/decrement, the state got corrupted. Example:

1. Load with value `6`.
2. Increment, value becomes `7` and is saved.
3. Increment again, value becomes `9`, since the loaded value is now `7` and two increments are applied to it.

**Then** I tried passing the initial state "from outside" like this:

```
var LOCAL_STORAGE_STATE_KEY = 'state';
var loadedState = JSON.parse(window.localStorage.getItem(LOCAL_STORAGE_STATE_KEY));
var initialState =  loadedState ? loadedState : {
    count: 0
};

function CounterReducer(state, action) {
    if (!state) {
        return initialState;
    }
    // ...
```

I now realize that this reducer is not pure either. The result is that every time page is reloaded, the last saved value is used as initial state, and then the actions are replayed, so the state becomes corrupted.. For example:

1. Load with value `0`.
2. Increment, value becomes `1`.
3. Reload, value is `1`, then replay of the increment makes it `2`.

Obviously, both ways are wrong and don't play well with DevTools (even though both of them seem to work on their own, despite reducers being impure).

What's the proper way to deal with this situation?

**Comment by sbichenko** [comment]
OK, sorry, figured it out. The initial state goes into the second parameter of `createStore`. It works now!

**Comment by gaearon** [comment]
Yep! See also https://github.com/elgerlambert/redux-localstorage.
