### ISSUE TITLE
Documentation and sample code mismatch

### ISSUE THREAD

**Issue by gouegd** [gaearon/redux-devtools#125]
Hey there! :)

The main readme says:

> DevTools is a store enhancer, which should be added to your middleware stack after applyMiddleware as applyMiddleware is potentially asynchronous

And just after:

> ```
const finalCreateStore = compose(
  // Enables your middleware:
  applyMiddleware(m1, m2, m3), // any Redux middleware, e.g. redux-thunk
  // Provides support for DevTools:
  devTools(),
  // Lets you write ?debug_session=<name> in address bar to persist debug sessions
  persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/))
)(createStore);
```

However, `compose`d functions are called right to left, so in this code `devTools()` will be called _before_ `applyMiddleware`, not _after_ like the doc says we must.

**Comment by gaearon** [comment]
You're right about the call order.
The intention was to encourage user to *write* it after (= below) `devTools()` in the `compose` chain.

If you see a better way of phrasing this please send a PR.
