### ISSUE TITLE
Ctrl+H doesn't work at osx + chrome47

### ISSUE THREAD

**Issue by vslinko** [gaearon/redux-devtools#126]
I've added `console.log(event.ctrlKey, event.keyCode);` at `handleKeyPress` and collect those results:

* `h` logged as `false 72`
* `ctrl` logged as `true 17`
* `ctrl`+`h` logged as `true 17` `true 8`

**Comment by gaearon** [comment]
Happy to accept a PR fixing this! (If you have one in mind.)

**Comment by vslinko** [comment]
I don't know how to fix that weird behaviour.

**Comment by gaearon** [comment]
Any chance keyboard layout is relevant?

**Comment by Shenlok** [comment]
This happens to me using Chrome on OSX too. A `keyCode` of 8 indicates the Backspace key, and `ctrl`+`h` is historically equivalent to the Backspace control character in unix terminal applications. It's possible that either Chrome or OSX is trying to emulate this.

**Comment by Shenlok** [comment]
Worth noting that this doesn't happen on the `keydown` event, only on `keypress`. On `keydown` I get `true 72` logged as I'd expect.

**Comment by Shenlok** [comment]
@vslinko Are you using an up-to-date version of `redux-devtools`? I could replicate the weird `keyCode` values you saw by listening on the `keypress` event, but the dev tools haven't used that event since [20th July](https://github.com/gaearon/redux-devtools/commit/013ef07f720bd79a9b8a49ae617dd35409e38a10).

**Comment by vslinko** [comment]
I get `true 8` on `keydown`:

![Alt text](https://monosnap.com/file/uj0EdCIzrnpLlw3pNoZ8FhDxaZbdeB.png)

**Comment by vslinko** [comment]
OS X 10.10.5
Chrome 47.0.2517.0

**Comment by vslinko** [comment]
When `ctrl` is pressed, `keypress` event doesn't emits at all.

**Comment by farin** [comment]
Ubuntu + Chrome 45

Ctrl + H toggles browser history

**Comment by gaearon** [comment]
Closing in favor of https://github.com/gaearon/redux-devtools-dock-monitor/issues/1.
Please help figure out the right API so everybody can customize shortcuts as they see fit.
