### ISSUE TITLE
Revert doesn't revert until a new action has been dispatched

### ISSUE THREAD

**Issue by ronag** [gaearon/redux-devtools#129]
Not sure what we are doing wrong. However, when we press "revert" in the devtool all the actions disappear however nothing happens in our UI. It is first when we dispatch an action (any action) that the revert is visible.

What might be causing this?

**Comment by ronag** [comment]
The reducers seem to run but the `mapStateToProps` is never invoked. I'm using immutable js if that has any possible relation to the issue.

**Comment by ronag** [comment]
Seems to be related to `batchedSubscribe(batchedUpdates)` enhancer.

```javascript
import { batchedSubscribe } from 'redux-batched-subscribe'
import { compose, createStore, applyMiddleware } from 'redux'
import { unstable_batchedUpdates as batchedUpdates } from 'react-dom' // eslint-disable-line camelcase

if (process.env.NODE_ENV === 'development' && process.env.IS_BROWSER) {
  const { devTools, persistState } = require('redux-devtools')
  enhancers = [
    //batchedSubscribe(batchedUpdates) // works without this line
  ]
  .concat(enhancers)
  .concat([
    devTools()
  ])
}

export default function(initialState) {
  return compose(...enhancers)(createStore)(appReducer, initialState)
}
```

**Comment by gaearon** [comment]
Try putting it *after* `devTools()`?

**Comment by ronag** [comment]
Yes, putting it after `devTools()` solves the issue.
