### ISSUE TITLE
Communicating with debug sessions

### ISSUE THREAD

**Issue by onemanstartup** [gaearon/redux-devtools#131]
I wanted to ditch server when developing my app, so i can postpone creating api. To do this i need a way to make functionality where i could open 2 tabs and have 2 different users who could communicate with each other. Is there any way for subscribing for debug_session changes in another tab?

**Comment by onemanstartup** [comment]
This is probably out of scope and my problem :)

**Comment by gaearon** [comment]
See how `persistState` works—shouldn't be hard to make a custom version that does something else.
