### ISSUE TITLE
'Ctrl + h' not working on Chrome + Linux

### ISSUE THREAD

**Issue by rodrigobac** [gaearon/redux-devtools#14]
I searched a little and just discovered that Chrome always return false to event.ctrlKey and other keys (e.g. event.shiftKey) on keypress.

So, the hide function doesn't work on Chrome + Linux (34+ as far as I know).

**Comment by pburtchaell** [comment]
Interesting. Did anyone mention a work-around? I have implemented key combinations like this before and haven't had any issues in Chrome.

**Comment by rodrigobac** [comment]
I'll look for workarounds (Having "ctrl" shotcuts in my actual project would be great). But, so far, none of them worked.

**Comment by rodrigobac** [comment]
I've managed to fix by just changing the 'keypress' event to 'keydown' event (yeah, hours looking for workarounds and just tried that now).

**Comment by pburtchaell** [comment]
Cool. Looks like it was merged in so you should be :100: here.

**Comment by gaearon** [comment]
Out in 0.1.2, thank you a lot.
