### ISSUE TITLE
update error.

### ISSUE THREAD

**Issue by geminiyellow** [gaearon/redux-devtools#141]
i update my package,

```
-    "react-redux": "^1.0.1",
+    "react-redux": "^2.0.0",

-    "redux": "^1.0.1",
+    "redux": "^2.0.0",

-    "redux-devtools": "^1.1.2",
+    "redux-devtools": "^2.0.0",
```

but i got a error,

```
Warning: React can't find the root component node for data-reactid value `.0.$debugPanel.0.1`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
```

who can tell me why?

**Comment by gaearon** [comment]
>If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.

Have you tried verifying whether this is the case?
See the issue [described here](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375).

I'm closing because it's unrelated to Redux DevTools—it's duplicate React in `node_modules` that is the issue.
