### ISSUE TITLE
Use findDOMNode from react-dom

### ISSUE THREAD

**Issue by dariocravero** [gaearon/redux-devtools#143]
Hi @gaearon, now that `0.14` is officially out, would you accept a PR that uses `findDOMNode` from `react-dom` instead of `react`?

**Comment by gaearon** [comment]
I will update my packages to use 0.14 when I get back from vacation, the day after tomorrow.
In the meantime I ask you to tolerate a couple of warnings that don't really break any code. ;-)

**Comment by dariocravero** [comment]
Thanks! I'm totally cool with that, just wanted to help :) Enjoy your holidays ;)
