### ISSUE TITLE
Warning with React v0.14.0

### ISSUE THREAD

**Issue by heikkilamarko** [gaearon/redux-devtools#145]
FYI,

When using redux-devtools with React v0.14.0, the following warning is printed to the browser console:

`Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.`

**Comment by nicgordon** [comment]
It will be fixed soon. See here: https://github.com/gaearon/redux-devtools/issues/143

**Comment by gaearon** [comment]
Please search existing issues before posting new ones, thanks!
