### ISSUE TITLE
[Announcement] Please don't create React 0.14-related PRs

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux-devtools#152]
Hi all,

Thanks a lot for sending 0.14-related PRs.
I know it's out, and I'm working on releasing updates for Redux-related packages.

Currently, sending PRs doesn't help because it's not hard for me to fix the warnings—the issue is in coordinated release of all packages (React Redux, DevTools, React Transform, etc) and fixing compatibility issues in the tooling. I will do my best to transition everything to 0.14 this week.

**In the meantime, please don't send PRs related to React 0.14 to Redux and related projects.**

Thanks.

**Comment by nickhudkins** [comment]
If there's anything any of us can do to help out please let us know :)

**Comment by gaearon** [comment]
Please try 3.0 Beta 2 and leave feedback.
It includes React 0.14 support: https://github.com/gaearon/redux-devtools/releases/tag/v3.0.0-beta-2

**Comment by gaearon** [comment]
Reopening because people keep creating them :stuck_out_tongue: 
Use 3.0 Beta!
