### ISSUE TITLE
Better space usage in DebugPanel view

### ISSUE THREAD

**Issue by kromit** [gaearon/redux-devtools#153]
I use a full HD display and under some circumstances I can only see 4-5 last actions happened because of heavy vertical padding/margin usage in the styles. (2-3 visible actions with Chrome dev tools opened)

How about an option to remove all the vertical padding/margin styles at all to maximize the space usage? I mean I like the aesthetics but usability and productivity is more important here.

**Comment by gaearon** [comment]
Can you make a screenshot so we can get a better idea of your setup?

**Comment by kromit** [comment]
Current state
![current state](https://cloud.githubusercontent.com/assets/5220821/10539782/91e014b2-7402-11e5-9f7a-ec89c7743063.png)

Desired state
![desirable](https://cloud.githubusercontent.com/assets/5220821/10539785/98469eb6-7402-11e5-8b75-a46dc64983b4.png)

**Comment by FredyC** [comment]
Well I think that spacing shouldn't be changed as it could introduce accidental clicks on something you didn't wanted. Much better solution could be automatic collapse basically to see just `state` and `action` in there by default. Or maybe make that configurable...

**Comment by kromit** [comment]
Since the panel is designed specially for debugging, the is a really small change the panel is seen by someone who does not know what he is doing. The probability of accidental click will be much lower in comparison to the currently almost persistent need to scroll up and down. However I also think it should be configurable. 

On the configurability: I am not a friend of inline React styles since I do work with less ans sass, so for me the best solution would be the optional disabling of all inline styes and additional usage of CSS classes so everybody can have its own style. Inline styles dictate the view with no option for any customization.

**Comment by gaearon** [comment]
Accidental don't happen because somebody doesn't know what they're doing. :-) They happen because we are people, not robots.

**Comment by kromit** [comment]
Right. I mean it is not that severe since the target user group does know how to handle it :)

**Comment by gaearon** [comment]
Even with the current version I often misclick because the click area isn't large enough. Knowing what to do isn't enough. :-)

**Comment by kromit** [comment]
So configurable styles would allow you to make it bigger more easily...? ;D

**Comment by gaearon** [comment]
I'm closing this issue because it is not directly actionable in this repo anymore, as the log monitor has been separated. The issue now lives as https://github.com/gaearon/redux-devtools-log-monitor/issues/1, and a PR to fix it is welcome.
