### ISSUE TITLE
Always re-running actions?

### ISSUE THREAD

**Issue by ronag** [gaearon/redux-devtools#156]
Always re-running actions as soon as a new action is dispatched makes things very slow for us. After like 12 actions our application goes to its knees unless we press "commit". Is this a known limitation or are we doing something wrong?

**Comment by FredyC** [comment]
Have you tried updating to latest devtools? There was some changes related to that.

**Comment by gaearon** [comment]
This should have been solved in 2.1.5.
We have tests for this.
Please reopen if not.
