### ISSUE TITLE
replaceReducer throws error

### ISSUE THREAD

**Issue by dferber90** [gaearon/redux-devtools#16]
## Problem

When trying to replace the reducer, the dev-tools throw this error:
`Uncaught TypeError: Cannot read property 'undefined' of undefined`

```
`Uncaught TypeError: Cannot read property 'undefined' of undefined
unliftState	@	devTools.js:189
getState	@	devTools.js:205
selectState	@	createConnector.js:89
handleChange	@	createConnector.js:82
(anonymous function)	@	Store.js:53
dispatch	@	Store.js:52
replaceReducer	@	Store.js:43
(anonymous function)	@	App.js:46
```

## Reproduction steps
I've used the *counter* example to verify the behavior. Modifying `containers/App.js` by adding the following lines after `const store = finalCreateStore(reducer);`

```js
// ..example code
const reducer = combineReducers(reducers);
const store = finalCreateStore(reducer);

// code for error reproduction
setTimeout(function () {
  console.log('replacing reducer')
  store.replaceReducer(reducer)
}, 5000)

// example code continues..
export default class App extends Component { // ..
```
Then just run the example code and wait for 5 seconds. The error appears in the browser console.
Error appears without `setTimeout`, too. I just used it to simulate code loaded later on.

## Question
Am I trying to do something that is not allowed or is this a legitimate bug?
The reason I am attempting to do this is because I am trying to make code splitting work.

**Comment by gaearon** [comment]
Oh, code splitting! Share your findings when you get it working :D
I'll look into this asap.

**Comment by gaearon** [comment]
It's a bug in devTools. Will fix soon.

**Comment by dferber90** [comment]
Yes, I'll share in case I am successful. Proper code splitting is quite challenging! :)

Thanks for looking into it

**Comment by gaearon** [comment]
Out in 0.1.2, thank you for reporting.

**Comment by dferber90** [comment]
That was fast! Thanks :)

**Comment by gaearon** [comment]
Let me know if it works ;-)

**Comment by gaearon** [comment]
Also props for making a badass-formatted bug report, it's a maintainer's dream.

**Comment by dferber90** [comment]
Just tried it and it works 🎉Sure :)
