### ISSUE TITLE
[Counter example] process.env.NODE_ENV is 'undefined'

### ISSUE THREAD

**Issue by vieks** [gaearon/redux-devtools#162]
https://github.com/gaearon/redux-devtools/blob/next/examples/counter/src/store/configureStore.js

Why make this test

```
if (process.env.NODE_ENV === 'production')
```
since the the code is executed on client side therefore process.env.NODE_ENV is undefined ?

**Comment by gaearon** [comment]
We assume that the consumer is going to envify their code—either with something like [loose-envify](https://github.com/zertosh/loose-envify) or `DefinePlugin` in Webpack.

This is a solid assumption to make because you should never run React in production without envifying it—or you'll get a slow development version.

**Comment by vieks** [comment]
ok thanks dude !

But now I am wondering about one thing, why make this kind of test on the client ?
I may misunderstood something... but the server side will be not a better place for this ?
Or webpack internally is smart enough to prevent the bloating of 'bundle.js' file so it will make http asset request only when needed ?

**Comment by gaearon** [comment]
There are no HTTP requests involved here.
Everything is compiled statically.

In development, `process.env.NODE_ENV` is replaced by envify (or `DefinePlugin`) with an `undefined` or `'development'` (depends how you set it up), so Webpack bundles both files.

However in production, `process.env.NODE_ENV` is replaced **statically** with `'production'` string, and then Uglify **statically** uses dead code elimination to kill `if (false)` branches, and as the result, **there is no `require()` to the development-only module in the production module compilation result**. Then, Webpack bundles only the files necessary for the production into a large JavaScript bundle. Not at any point there are HTTP requests or servers. It's all static JS compilation.

**Comment by gaearon** [comment]
Webpack does not make HTTP requests to `import`ed or `require`d files.
It's not RequireJS.

They are all resolved at compile time and compiled into one large JS bundle.

**Comment by vieks** [comment]
Good explanation.
Thus the magic behind the 'webpack production compile' process is based on the Uglify  to remove unreachable code after process.env replacement with static string.

Thanks of lot man to take your time to help. Your works for react+flux community is impressive !!!!

**Comment by gaearon** [comment]
>Thus the magic behind the 'webpack production compile' process is based on the Uglify to remove unreachable code after process.env replacement with static string.

Yup. Same way it works for React itself—you should always envify + uglify it before using NPM build in production.

Cheers!

**Comment by vieks** [comment]
Wow your are smart and blazing fast... Truly an awesome guy ;)
Cheers

**Comment by mrtho1** [comment]
Late to the party, but what am I missing here.  I'm constantly getting the console warning:

`You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.`

When running against a minified build.

If I do a fresh/clean npm install I get the following in node_modules/redux/dist/redux.js:
`        if (("development") !== 'production' && typeof isCrushed.name === 'string' && isCrushed.name !== 'isCrushed') {
          (0, _warning2["default"])('You are currently using minified code outside of NODE_ENV === \'production\'. ' + 'This means that you are running a slower development build of Redux. ' + 'You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify ' + 'or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) ' + 'to ensure you have the correct code for your production build.');
        }
`

which looks like the envify has already been run.  I've tried installing with NODE_ENV set to production and npm set production true and the same code is generated.  How do I get the proper env string injected in this file?
