### ISSUE TITLE
No more visibleOnLoad in v3?

### ISSUE THREAD

**Issue by erikras** [gaearon/redux-devtools#163]
I'm using `redux-devtools@3.0.0-beta-3`, and I see that the `visibleOnLoad` prop has gone away.

Is there a new way to have it default to hidden?

**Comment by erikras** [comment]
Nevermind. Figured it out. Using `DockMonitor`:
```js
<DockMonitor
    toggleVisibilityKey="H"
    changePositionKey="Q"
    defaultIsVisible={false}> // <--------------- Bingo!
  <LogMonitor/>
</DockMonitor>
```

**Comment by gaearon** [comment]
That's it!
