### ISSUE TITLE
Using "next" devtools blocks global window keyboard shortcuts with CTRL or ALT

### ISSUE THREAD

**Issue by eXtreme** [gaearon/redux-devtools#169]
So I'm using "next" redux devtools but having them enabled with log-monitor blocks keyboard shortcuts like.. CTRL+R (really handy), copy/paste (well..), writting Polish diacritics like ALT+A for "ą" or ALT+O for "ó" or any other. Every combination I try with CTRL or ALT is blocked except for CTRL+H for hiding/showing log monitor.
When I build my files with production env (so disabled devtools) - everything works without any problems.

**Comment by gaearon** [comment]
This was fixed in https://github.com/gaearon/redux-devtools-dock-monitor/pull/2.
It will be published with next release.

**Comment by eXtreme** [comment]
Oh sorry then, I've checked the wrong repo..
