### ISSUE TITLE
readme in next branch is wrong

### ISSUE THREAD

**Issue by janmarek** [gaearon/redux-devtools#172]
Hi,
I tried to install dev-tools 3.0.0 beta 3 according to instructions in next branch. Unfortunately function devTools does not exist in dev-tools. There is only createDevTools which requires a parameter. I don't know if that is a correct function now nor which value should I put in it.

**Comment by gaearon** [comment]
It's not wrong. It's not written yet. That's why it's not merged to `master` yet. :-)

**Comment by drinchev** [comment]
:+1: I also didn't notice that.
