### ISSUE TITLE
Force LTR on the wrapper div

### ISSUE THREAD

**Issue by mohebifar** [gaearon/redux-devtools#174]
I think we need to set `direction: ltr` on the parent div to override `direction: rtl` on body element. Given the fact that` redux-devtools` elements do not have any classes, it simply fixes the issue on RTL pages. (The image below)

![selection_021](https://cloud.githubusercontent.com/assets/6104558/10791851/8abadd88-7d9f-11e5-9fd9-c01dfabf230f.png)

**Comment by mohebifar** [comment]
Ah, It seems to be something related to the monitor. But I'm still not sure where to follow this issue.

**Comment by gaearon** [comment]
Please feel free to submit a PR to https://github.com/gaearon/redux-devtools-log-monitor, that code lives there now.
