### ISSUE TITLE
createDevTools  and addComponentAsRefTo

### ISSUE THREAD

**Issue by tcurdt** [gaearon/redux-devtools#177]
I am not sure if it's the fact it's the beta or I am doing something wrong. I have:

    react-redux@4.0.0
    redux@3.0.4
    redux-devtools@3.0.0-beta-3
    redux-devtools-dock-monitor@1.0.0-beta-3
    redux-devtools-log-monitor@1.0.0-beta-3
    redux-thunk@1.0.0
    react@0.14.0
    react-dom@0.14.1

and then I have DevTools.js

    import React from 'react';
    import { createDevTools } from 'redux-devtools';
    import LogMonitor from 'redux-devtools-log-monitor';
    import DockMonitor from 'redux-devtools-dock-monitor';

    export default createDevTools(
      <DockMonitor toggleVisibilityKey='H' changePositionKey='Q'>
        <LogMonitor />
      </DockMonitor>
    );

but as soon as I include like this

    import DevTools from './DevTools';

    export default class Root extends Component {
      render() {
        return (
          <div>
            <DevTools />
          </div>
        );
      }
    }

I am getting

> Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

**Comment by gaearon** [comment]
This means you have two Reacts somewhere in `node_modules`.

**Comment by gaearon** [comment]
Probably because your `react` and `react-dom` versions don't match, you got `react@0.14.1` installed inside `react-dom`.
