### ISSUE TITLE
Up react-json-tree version to 0.3.0

### ISSUE THREAD

**Issue by redexp** [gaearon/redux-devtools#181]
It's safe to up react-json-tree version to 0.3.0 which now can render `undefined` and `function` types

I ran tests and they all passed

**Comment by gaearon** [comment]
It's done in the separated [log monitor](https://github.com/gaearon/redux-devtools-log-monitor/). The corresponding release will be up in a week or so, after I finish my work on Redux Egghead videos. One thing at a time.
