### ISSUE TITLE
Filter actions to remove server push

### ISSUE THREAD

**Issue by nite** [gaearon/redux-devtools#184]
Hi, I have an app with a server feed & many events updating state via actions - is there way to filter these out to leverage redux-devtools for user actions only, if not I cant really use it! 

this is similar to [issue 77](https://github.com/gaearon/redux-devtools/issues/77) however I dont see a solution out there.

Any other suggestions of a good forum to discuss this - maybe there's a way with redux to update the state without actions?

**Comment by zalmoxisus** [comment]
Use [redux-devtools-log-monitor-filterable](https://github.com/zalmoxisus/redux-devtools-log-monitor-filterable) as described [here](https://github.com/zalmoxisus/redux-devtools-log-monitor-filterable#containersdevtoolsjs).

**Comment by gaearon** [comment]
Relevant: https://github.com/zalmoxisus/redux-devtools-log-monitor-filterable/issues/2

**Comment by gaearon** [comment]
Please use https://github.com/zalmoxisus/redux-devtools-filter-actions. It can be composed with any monitor.
