### ISSUE TITLE
DevTools 3 with Redux Router Error

### ISSUE THREAD

**Issue by damassi** [gaearon/redux-devtools#187]
First, excellent work on this new version -- it feels much nicer and more usable than the last. So the issue I'm running into is using DevTools alongside Redux Router. If you place the dev tools at the end of the compose chain everything boots and works fine, you can go backwards and forwards, but when you click 'Reset' it throws this error, the same error that is shown if you move the dev tools anywhere other than the end in `compose`:

<img width="474" alt="screen shot 2015-11-10 at 7 12 59 pm" src="https://cloud.githubusercontent.com/assets/236943/11083054/a903c260-87df-11e5-83ff-b36ab9ad4609.png">

One other thing I noticed is you can't expand the payload, though it correctly shows that there are updated keys. You can, however, expand the store state.

Could be configuration? Or a bug?

**Comment by ellbee** [comment]
Its a problem with `redux-router`. The initial state of the `redux-router` store is set to null and then to the current router state when the `listen` callback from `history` fires immediately after setting it up. When reset is dispatched the `redux-router` store is reset to null but the listen callback doesn't fire. I have a workaround that will fix this but I don't really like it. I'll open up a discussion on `redux-router` when I get some time later and see if anyone has any better ideas.

**Comment by gaearon** [comment]
Yeah it's a problem there. We'll likely be switching to `redux-simple-router` anyway.
