### ISSUE TITLE
error in Promise actions when commenting devtools() middleware

### ISSUE THREAD

**Issue by Raffiki** [gaearon/redux-devtools#188]
uncommenting `devTools()` middleware gives me a an error on `Promise` actions.

```
import { createStore, compose, combineReducers, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import createLogger from 'redux-logger';
import * as reducers from '../reducers';
import api from '../middleware/api';
import { ReduxRouter, reduxReactRouter, routerStateReducer} from 'redux-router';
import { default as createHistory } from 'history/lib/createBrowserHistory';
import { devTools } from 'redux-devtools';
import * as routes from '../routes';

const logger = createLogger();
let middleware = [thunk, api];

const finalCreateStore = compose(
    reduxReactRouter({routes, createHistory}),
    applyMiddleware(...middleware)
    //devTools()
)(createStore);

```

results in an error

`Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.` In this case the action is a `Promise`.

Uncommenting the `devTools()` makes everything work again. 

a little debugging:

in the working version https://github.com/rackt/redux/blob/master/src/utils/isPlainObject.js#L21 returns true as they are both `function Object() { [native code] }`

in the non-working: 
`fnToString(constructor)` returns `"function Promise() { [native code] }"`

Can anyone give me insight how the `Promise` contructor is altered?

versions: 

````
    "redux": "^3.0.2",
    "redux-devtools": "^2.1.5",
    "redux-router": "^1.0.0-beta3",
    "redux-thunk": "^1.0.0",
````

**Comment by gaearon** [comment]
What is `api`? Can you give the source code for it?

**Comment by Raffiki** [comment]
Sure, it's a copy of own of your examples I believe: https://gist.github.com/Raffiki/641d145078069cf41297

**Comment by Raffiki** [comment]
```
function getInitialData() {
    return function (dispatch, getState) {
        return dispatch(
            Promise.all([
                 dispatch(fetchPartA),
                 dispatch(fetchPartB)
            ])
        ).then((responses) => {
```

yeah, I did this...devTools wraps this promise action in an object. That explains why it didn't fail.
But without devTools, calling `next()` middleware with a `Promise` is not a good idea. My bad...
I'll find a way around
