### ISSUE TITLE
question: does the 3.x branch support something like visibleOnLoad yet?

### ISSUE THREAD

**Issue by tony-kerz** [gaearon/redux-devtools#189]
hi dan,

love what you are doing with dev-tools!

kicking the tires on 3.x beta and wondering if there is something like `visibleOnLoad` yet?

(straight up `visibleOnLoad` doesn't seem to work for me).

best,
tony.

**Comment by chentsulin** [comment]
It seems be renamed to `defaultIsVisible`:

https://github.com/gaearon/redux-devtools-dock-monitor/blob/master/src/DockMonitor.js#L13

**Comment by tony-kerz** [comment]
boom! thanks @chentsulin :+1: 

```
export default createDevTools(
  <DockMonitor toggleVisibilityKey='H' changePositionKey='W' defaultIsVisible={false}>
    <LogMonitor />
  </DockMonitor>
)
```
