### ISSUE TITLE
Set up online demo

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux-devtools#19]
We should have an official online demo, just like http://lapanoid.github.io/redux-devtools-gentest-plugin/.

@lapanoid Is this something you'd like to contribute? Basically we just want to run the TodoMVC with monitor just like in your repo.

**Comment by lapanoid** [comment]
Sure, will do that.

**Comment by lapanoid** [comment]
Made PR for this https://github.com/gaearon/redux-devtools/pull/20

**Comment by lapanoid** [comment]
Also this need to be merged https://github.com/gaearon/redux-devtools/issues/19

**Comment by lapanoid** [comment]
We also need to recompile todo bundle from time to time.

**Comment by gaearon** [comment]
This is superseded by #20 and #21 so I'll close the issue.
We'll have a demo for 3.0 when it's out.
