### ISSUE TITLE
Devtools block keyboard shortcuts 

### ISSUE THREAD

**Issue by teosz** [gaearon/redux-devtools#192]
Devtools is blocking keyboard shortcuts like copy/paste (ctrl-c/ctrl-v), select all (ctrl-a), etc..

**Comment by DiogoDoreto** [comment]
https://github.com/gaearon/redux-devtools-dock-monitor/pull/2

**Comment by gaearon** [comment]
Duplicate of https://github.com/gaearon/redux-devtools-dock-monitor/pull/2.
This will be fixed in the final 3.0 release.

**Comment by gaearon** [comment]
Fixed as of 3.0.
