### ISSUE TITLE
Source maps not working

### ISSUE THREAD

**Issue by ddeath** [gaearon/redux-devtools#193]
Hi there,

I use [este dev stack](https://github.com/este/este) and when I appended a redux-devtools, then source maps stopped working - when some error occure it does not show the exact file where it occures...

**Comment by matystl** [comment]
try use dev tools as [chrome extension](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd).Then dev tools will not be part of your compiled application. 

And for future put this isue in este repo not in this one. Or provide example with redux and redux devtools only where it's not working.

**Comment by ddeath** [comment]
Ok, sorry. So I did.
From redux git repo example [todomvc](https://github.com/rackt/redux/tree/master/examples/todomvc):

changed configureStore.js in folder store to:

```
import { createStore, compose } from 'redux'
import rootReducer from '../reducers'

export default function configureStore(initialState) {

  const createReduxStore = compose(window.devToolsExtension ? window.devToolsExtension() : f => f);
	
  const store = createReduxStore(createStore)(rootReducer, initialState)

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('../reducers', () => {
      const nextReducer = require('../reducers')
      store.replaceReducer(nextReducer)
    })
  }

  return store
}
```

and line infile [reducers/todos.js L 24](https://github.com/rackt/redux/blob/master/examples/todomvc/reducers/todos.js#L24) changed like this (todo => todox):

```
return state.filter(todox =>
```

And if I do not have extension installed, I get an error:
```
Uncaught ReferenceError: todo is not defined
(anonymous function)	@	todos.js?6905:25
...
```

And if I turn extension on:
```
ReferenceError: todo is not defined
at eval (eval at <anonymous> (http://localhost:3000/static/bundle.js:2407:2), <anonymous>:29:16)
...
```

**Comment by matystl** [comment]
I did this steps and it's working: 
* clone repo
* `npm install `
* `cd examples/todomvc`
* `npm install`
* `npm run start`
change `configureStore.js`  to what you posted 

Then i disable extension and try it again and it was also working. 

So can you provide repo with your changes just to be sure that you didn't edit something accidentaly? If not than pls provide what OS and browser version are u using?

**Comment by ddeath** [comment]
Ok here are steps:

* git clone https://github.com/ddeath/redux.git ./
* cd examples/todomvc/ 
* nvm use 4.2.2
* npm install
* node server.js

and then on http://localhost:3000 i tested the extension and it behaves as I described above

System specs:
OS: Debian GNU/Linux 8 (jessie) 64bit
Browser: Google Chrome Version 46.0.2490.86 (64-bit)

**Comment by matystl** [comment]
Sorry i thought extension is not working for you not source maps (my fault).

So i try minimal example from redux repo(todomvc) and hot reloading is working but after you make change(or mistake) in reducer it will be reloaded but source maps are pointing to source file from first load of page. So it will be probably error of webpack. Or maybe it's not supported in webpack. 

Would be nice to try example without redux only with webpack hot reloading if that would be working(if no then post issue in webpack repo).

**Comment by ddeath** [comment]
well hot reloading is not a problem at all. It is all working until I install the extension.

**Comment by zalmoxisus** [comment]
Hey @ddeath,

This comes from [devTools.js#L44](https://github.com/gaearon/redux-devtools/blob/0a1458cdbd50ea2a345fb8d913f7e0d1c763f42b/src/devTools.js#L44).

According to [Chrome issue](https://code.google.com/p/chromium/issues/detail?id=376409):
> There is no way to fix it for Error.stack property because this property is generated by V8 which know nothing about source map, DevTools just replace links from Error.stack in console log and trace in sidebar.

Related to https://github.com/webpack/webpack/issues/1646.

The only way to get it fixed is to remove try-catch and the error info in the Redux DevTools, but I figure it is one of the core features of DevTools. @gaearon, what do you think? Maybe, at least, we'd make this configurable, so we may pass `dismissErrors=false`?

**Comment by zalmoxisus** [comment]
If you use the extension, it is fixed in `v0.4.4`.

**Comment by gaearon** [comment]
Whatever the source map problem is, it's not with DevTools, but with Webpack configuration or other tooling.

**Comment by zalmoxisus** [comment]
@ddeath, it seems to work now in Chrome 47. Could you confirm?

**Comment by gaearon** [comment]
Please check if it's better in 3.0.1.

**Comment by jdavault** [comment]
import { legacy_createStore as createStore, applyMiddleware } from "redux";
import reducers, { initialState } from "./reducers";
import thunkMiddleware from "redux-thunk";
import { composeWithDevTools } from "@redux-devtools/extension";

const composeEnhancers = composeWithDevTools({ serialize: true });

export const store = createStore(
  reducers,
  initialState,
  composeEnhancers(applyMiddleware(thunkMiddleware))
);

//WORKED FOR ME ....

**Comment by markerikson** [comment]
@jdavault note that today you should be using our official Redux Toolkit package, which automatically does all that store configuration work for you:

- https://redux.js.org/tutorials/essentials/part-2-app-structure#creating-the-redux-store
- https://redux.js.org/usage/migrating-to-modern-redux#store-setup-with-configurestore
