### ISSUE TITLE
What do the Buttons do

### ISSUE THREAD

**Issue by banderson5144** [gaearon/redux-devtools#196]
What does Sweep, Revert, and Commit do?

**Comment by ellbee** [comment]
Commit 'saves' a state, which Revert will return to. Sweep will remove any actions that have been disabled.

**Comment by gaearon** [comment]
Please see https://github.com/gaearon/redux-devtools-log-monitor/blob/master/README.md#features.

**Comment by iamakulov** [comment]
I believe this should be described in the readme. Just spent 10 minutes searching for what the “Commit” button does.

@gaearon, should I make a PR adding this?

**Comment by gaearon** [comment]
It is described in README for the relevant project: https://github.com/gaearon/redux-devtools-log-monitor/blob/master/README.md#features.

I’d be happy to accept a PR that adds a link to the relevant part of *that* README though :-)

**Comment by iamakulov** [comment]
Sure! Will do it in a couple of days :–)
