### ISSUE TITLE
ActionsById immutability (next branch)

### ISSUE THREAD

**Issue by minedeljkovic** [gaearon/redux-devtools#198]
Shouldn't actionsById be immutable part of instrument reducer? Isn't that more in the spirit of redux, or is there some specific reason not to be?

I am referring to this code inside [instrument.js](https://github.com/gaearon/redux-devtools/blob/next/src/instrument.js):

```js
      case ActionTypes.PERFORM_ACTION: {
        if (currentStateIndex === stagedActionIds.length - 1) {
          currentStateIndex++;
        }
        const actionId = nextActionId++;
        // Mutation! This is the hottest path, and we optimize on purpose.
        // It is safe because we set a new key in a cache dictionary.
        actionsById[actionId] = liftedAction;
        stagedActionIds = [...stagedActionIds, actionId];
        // Optimization: we know that only the new action needs computing.
        minInvalidatedStateIndex = stagedActionIds.length - 1;
        break;
      }
```

I am making wrapper component for a [LogMonitor](https://github.com/gaearon/redux-devtools-log-monitor) that filters actions to be logged and trying to implement pure equality optimization (since LogMonitor component is getting new props frequently), but cannot do it because of actionsById mutability.

**Comment by minedeljkovic** [comment]
Just now I spotted a `Mutation!` comment. My bad.

**Comment by gaearon** [comment]
Generally you shouldn't care about `acitonsById` mutation on adding because `stagedActionIds` would change anyway.
