### ISSUE TITLE
Cannot Copy/Paste

### ISSUE THREAD

**Issue by mlucool** [gaearon/redux-devtools#200]
Hi,

I cannot highlight to copy/paste the data in the devtools default UI. It won't highlight the text on using chrome 47.

Another very useful feature would be to serialize either the action or the state to JSON and then to the clipboard.

**Comment by chentsulin** [comment]
Relative to : https://github.com/chibicode/react-json-tree/issues/10

**Comment by mlucool** [comment]
Thanks, I'd be happy with an export button. Solves 80% of my use cases.

I do believe the copy paste should be enabled too. Detect a click/drag instead of just a click isn't impossible, so the UX issue they are having is solvable in a better way than always disabling.

**Comment by gaearon** [comment]
This is only relevant to https://github.com/gaearon/redux-devtools-log-monitor so please file the issue there.
