### ISSUE TITLE
Improve rendering of action payloads that are `Error`s

### ISSUE THREAD

**Issue by MaartenVerbaarschot** [gaearon/redux-devtools#201]
I'm handling action errors as specified in [Flux Standard Action](https://github.com/acdlite/flux-standard-action):

```
{
  type: 'ADD_TODO',
  payload: new Error('my error'),
  error: true
}
```

And currently, these are renderd by Redux Dev Tools as:

```
ADD_TODO
action 2 keys
payload: {} 0 keys
error: true
```

I think it would be good to check if the payload is an `Error`, and if so, render it stringified instead of with `<JSONTree/>`.

For now, I'm solving it by adding an errorLoggerMiddleware to do this:

```
const errorLoggerMiddleware = store => next => action => {
  if (action.error && !isUndefined(console)) {
    console.error(action);
  }
  return next(action);
};
```

But of course, it would be nicer to have the DevTools already cover this :). Do you agree? I can make a PR if you think this is the right approach.

**Comment by gaearon** [comment]
Sounds good to me, give it a go!
Should be in https://github.com/gaearon/redux-devtools-log-monitor now.
