### ISSUE TITLE
Now supports React v0.14?

### ISSUE THREAD

**Issue by kennetpostigo** [gaearon/redux-devtools#206]
Hello,

Just wondering if `redux-devtools` now supports react v0.14 because I saw that the label for it coming soon was removed.

Also does this use `react-transform` for hot-reloading?

**Comment by MoOx** [comment]
I am currently using react 0.14 with the devtools. No problem.
Not sure for the hot loading.

**Comment by calesce** [comment]
Yes to the latter question, [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit) uses both react-transform and the latest Redux DevTools.

**Comment by gaearon** [comment]
Not sure what label you're referring but yes, since 3.0 stable it only supports 0.14+.
