### ISSUE TITLE
Import/export serialized state?

### ISSUE THREAD

**Issue by stuartsan** [gaearon/redux-devtools#209]
I'm wondering if it would be appropriate to add the following feature here, or in a related package like https://github.com/gaearon/redux-devtools-log-monitor, or if it'd be better to make it a totally separate thing: the ability to export to a file the serialized app state, and import it from a file as well. The use case I'm imagining is sharing app state between people via the file.

Any interest in this?

**Comment by lapanoid** [comment]
There is a monitor for this https://github.com/lapanoid/redux-import-export-monitor written by @calesce. We should upgrade it to latest devtools api.

**Comment by stuartsan** [comment]
Ah ok cool, thanks for the pointer!
