### ISSUE TITLE
Expected identifier error in IE8

### ISSUE THREAD

**Issue by kevana** [gaearon/redux-devtools#213]
Same as [react-redux #232](https://github.com/rackt/react-redux/issues/232), also affects dock-monitor and log-monitor.

**Comment by kevana** [comment]
If the solution is to switch back to CommonJS modules for now I can put a PR together

**Comment by gaearon** [comment]
If you have time please do create the PRs. Note that for backward compat the monitors should still have default exports, so the entry point might look pretty much like the code generated by Babel.

**Comment by gaearon** [comment]
We decided to not support IE8. React is also dropping IE8 compat guarantees in the next version.
