### ISSUE TITLE
Standalone examples

### ISSUE THREAD

**Issue by henryguykemp** [gaearon/redux-devtools#219]
Hi,

 I would like a standalone example of counter/todos. There are dependencies on the parent redux src folder which are not obvious. Could someone explain the dependencies/create a standalone example?

Henry

**Comment by zalmoxisus** [comment]
Removing [`resolve.alias`](https://github.com/gaearon/redux-devtools/blob/master/examples/todomvc/webpack.config.js#L20-L24) should help. Alternatively, you may use config from [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/todomvc/webpack.config.js).

**Comment by henrykempo** [comment]
Thanks, thats clear now.
