### ISSUE TITLE
Devtools bug when actions triggered by window's scroll

### ISSUE THREAD

**Issue by tracker1** [gaearon/redux-devtools#221]
I setup an container/component that dispatches actions on window resize/scroll, however, when I have the redux-devtools open, this event triggers when I scroll to the bottom and attempt to open the last state to inspect.

I was able to get to a state, where the event would fire endlessly as devtools continued to expand...  not sure about the display/render logic of the devtools container, but it's an issue for me.

-----

NOTE: I'm using these events to control certain parts of rendering (namely hiding/showing components at different sizes), as well as wanting to do some scroll spying.  I'm using [material-ui](http://www.material-ui.com/#/) which uses inline styles.

**Comment by zalmoxisus** [comment]
Wrap the monitor into a [filter monitor](https://github.com/zalmoxisus/redux-devtools-filter-actions), and add these actions there to be filtered. Autoscrolling the monitor when a new action appears is an intended effect.

**Comment by tracker1** [comment]
@zalmoxisus thanks, may need that...

In my case, I was able to resolve this, by inverting my position/size detection to only dispatch the event if the values actually changed...

https://github.com/tracker1/r3k-example/blob/master/client/containers/WindowEvents.jsx
https://github.com/tracker1/r3k-example/blob/master/client/actions/window/index.js

probably not the best way to handle this, but window/platform events should be *very* limited to begin with.
