### ISSUE TITLE
global is not defined - SetCache

### ISSUE THREAD

**Issue by hoodsy** [gaearon/redux-devtools#229]
When DevTools v3 isn't included in my babel-loader, I get the error ```global is not defined``` in the browser, tracing to this file:

```javascript
var cachePush = require('./cachePush'),
    getNative = require('./getNative');

/** Native method references. */
var Set = getNative(global, 'Set');

/* Native method references for those with the same name as other `lodash` methods. */
var nativeCreate = getNative(Object, 'create');

/**
 *
 * Creates a cache object to store unique values.
 *
 * @private
 * @param {Array} [values] The values to cache.
 */
function SetCache(values) {
  var length = values ? values.length : 0;

  this.data = { 'hash': nativeCreate(null), 'set': new Set };
  while (length--) {
    this.push(values[length]);
  }
}

// Add functions to the `Set` cache.
SetCache.prototype.push = cachePush;

module.exports = SetCache;



/*****************
 ** WEBPACK FOOTER
 ** ./~/redux-devtools/~/lodash/internal/SetCache.js
 ** module id = 245
 ** module chunks = 0
 **/
``` 

This started happening after upgrading to Babel 6, and can be worked around by setting ```global``` as an empty object in my **webpack config**:
```javascript
var path = require('path')
var webpack = require('webpack')

var config = {
  devtool: 'cheap-module-eval-source-map',
  target: 'node',
  entry: [
    'webpack-hot-middleware/client',
    './client/index'
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/'
  },
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.DefinePlugin({
        'process.env.NODE_ENV': '"development"',
        // 'global': {}, // WORKAROUND
        'global.GENTLY': false // superagent client fix
    })
  ],
  module: {
    loaders: [
      { test: /\.json$/, loaders: ['json'], },
      { test: /\.js$/,  loader: 'babel', exclude: /node_modules/ },
      { test: /\.js$/,  loader: 'eslint', exclude: /node_modules/ },
    ]
  },
  // build breaks on eslint without this workaround
  // https://github.com/MoOx/eslint-loader/issues/23
  eslint: {
    emitWarning: true
  },
  node: {
    __dirname: true, // superagent client fix
  },
}

module.exports = config;
```

Again, I only encountered this issue when upgrading to Babel 6 (and DevTools 3).

**Comment by gaearon** [comment]
Why doesn't this come up in examples in this repo?

**Comment by zalmoxisus** [comment]
Probably you let babel to process dependencies, see the explication [here](https://github.com/webpack/webpack-dev-server/issues/174#issuecomment-102391902).

**Comment by hoodsy** [comment]
@gaearon My fault - the fix was in the examples webpack config.

**Comment by gaearon** [comment]
What was it?

**Comment by hoodsy** [comment]
adding an alias:

```
resolve: {
    alias: {
      'redux-devtools': path.join(__dirname, 'node_modules', 'redux-devtools')
    }
  },
```

**Comment by gaearon** [comment]
I'm confused. Did you add or remove this alias to fix the problem? You definitely don't need it in your project. The examples in this repo have alias so that they reference the DevTools source rather than the version in node_modules because it makes DevTools easier to develop. It's not something you should copy.

**Comment by hoodsy** [comment]
I added the alias, and I no longer get global is not defined in the browser. I'm relatively new to Webpack, so can't claim to know why this worked as a fix.. the issue I was having wasn't mentioned elsewhere.

My loaders exclude node modules as well, and the only thing added to my webpack config was the alias.

**Comment by gaearon** [comment]
Can you post the project reproducing the problem?
Any chance you used npm link with DevTools?
Can you delete node_modules and try again?

**Comment by hoodsy** [comment]
I'm having trouble reproducing this. 

I had the ```global: {}``` workaround in place while making a number of application changes - it must have been a mistake I made elsewhere. I also removed the dependency ```redux-localstorage```, which has not been updated in a few months, but I'm still not sure the cause of the issue.

Apologies for the misguided issue!
