### ISSUE TITLE
separate-window devTools can use the full window

### ISSUE THREAD

**Issue by dts** [gaearon/redux-devtools#230]
Towards the end of the readme, there's a description of how to open the redux dev tools in a separate window.  On my machine this shows up using only part of the window.  To fix this, I insert an inline style in the document that full-sizes the dev tools root:

```js
popup.document.write('<style>#react-devtools-root > div > div { left: 0px !important; width: 100% !important; }</style><div id="react-devtools-root"></div>');
```

I can fork/change/PR if that's what's desired, but I though this might be easier.

**Comment by gaearon** [comment]
I think this is the kind of thing people can customize if they want to.
An inline style would probably be compact enough that we can include it in README though.

**Comment by zalmoxisus** [comment]
Actually, it uses only a part of window because it is wrapped in a dock monitor, which is not needed there. Use only LogMonitor and `div { width: 100%; height: 100% }`.

**Comment by gaearon** [comment]
Good point. Mind amending the README?

**Comment by zalmoxisus** [comment]
@gaearon, will do a pr. I even have [a gist](https://gist.github.com/zalmoxisus/de456d1192f31bf381c0), but have to check whether it is outdated.

**Comment by zalmoxisus** [comment]
Just tried the example from README, LogMonitor renders well on Chrome and Firefox (Safari somehow kill auto popups without warning but it's not related), any css changes aren't necessary. The point is just not to use DockMonitor, which is already [indicated there](https://github.com/gaearon/redux-devtools#or-open-them-in-a-new-window).
