### ISSUE TITLE
any chance we can get hot loading and all this goodness with Angular2?

### ISSUE THREAD

**Issue by born2net** [gaearon/redux-devtools#234]
any chance we can get hot loading and all this goodness with Angular2?

regards

Sean.

**Comment by gaearon** [comment]
I don't see why it wouldn't work with Angular 2.
Do you have any specific problem?

**Comment by born2net** [comment]
I was under the impression it was designed for React, I will google see if I can find some ng2 examples on how to deply... regards (by the way, do you speak Hebrew?)

**Comment by gaearon** [comment]
Alas, I don't speak Hebrew.

It's true that it's primarily for React but you can render it in a separate window as described in the walkthough. This way you'd just need to install React and paste that code snippet so it's be displayed separately from your app.

**Comment by born2net** [comment]
got it, tx!
