### ISSUE TITLE
support for ArrayLike objects

### ISSUE THREAD

**Issue by AvraamMavridis** [gaearon/redux-devtools#236]
Currently some of the ArrayLike objects are not "printed correctly" in the dock, e,g, ImmutableJS data structures, because of the way lodash"s `identity` function works. e.g. if you have a `List` you probably are interested for its contents rather than its internal representation. 

Lodash`s identity in this case will return: 
```javascript 
  Object {size: 4, _origin: 0, _capacity: 4, _level: 5, _root: null…}
```

...but you probably want to see the contents of the `List` and not the List's internal representation

```javascript
if ( isArrayLikeObject ( listOnTheState ) )
{
  identity( listOnTheState ).toArray(); 
}
```

Is there any plan for supporting ArrayLike objects like this? If this is indeed an issue I can provide the PR.

**Comment by gaearon** [comment]
Where do you see `identity` being used? `identity` is just a function that returns its argument so we're not "using" it in any specific sense. Also log monitor [has its own repository](https://github.com/gaearon/redux-devtools-log-monitor) which is probably where you'd like to report the issue. Under the hood it uses [react-json-tree](https://github.com/chibicode/react-json-tree) which [should support any Iterables](https://github.com/chibicode/react-json-tree/blob/db4e2ce21808c7b8c2bddcb049c896d005ae32c8/src/grab-node.js#L48). If you can reproduce the issue with react-json-tree, please file it there. I don't think there's anything actionable in this repo, so I'm closing.
