### ISSUE TITLE
Idea: Actions UI

### ISSUE THREAD

**Issue by khankuan** [gaearon/redux-devtools#239]
Was wondering about a small ui panel with a select dropdown showing all available actions (with fuzzy search) as well as the params. It might be useful for firing actions manually.

**Comment by gaearon** [comment]
That’s a good idea. I think it’s best to do this as a custom monitor. Would you like to try?

**Comment by khankuan** [comment]
Any opinion on how would users register all their actions?

**Comment by khankuan** [comment]
Woohoo someone built something similar: https://github.com/YoruNoHikage/redux-devtools-dispatch
Lets close this :)
