### ISSUE TITLE
Reducer hotswapping

### ISSUE THREAD

**Issue by donabrams** [gaearon/redux-devtools#24]
I've been trying to get reducer hot swapping working all day, to no avail. This is most recent attempt:

https://github.com/donabrams/react-redux-universal-hot-example/blob/master/src/reducers/test.js#L10

This is the only (non-actionable) console message I got:
```
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
log-apply-result.js?d762:13
[HMR]  - 272
```

Am I doing something wrong? Is there something I need to do to support reducer hot reloading as in https://github.com/gaearon/react-hot-loader/issues/163?

**Comment by erikras** [comment]
You repository is working fine for me. I did:

1. `npm install`
2. `npm run dev`
3. Loaded `localhost:3000`
4. Clicked on the count to increment it a couple of times.
5. Edited `App.js` to change `clickCount {clickCount}` to `clickCount: {clickCount}` (added colon)

And it hot reloaded and kept the count in state.

**Comment by gaearon** [comment]
@erikras 

You're editing component, I think @donabrams is editing the reducer.

For reducer hot swapping to work, the example needs to be modified so that `store` is created inside the root component file instead of `client.js`, like here: https://github.com/gaearon/redux/blob/98ab1de4df0da56bd1f95e1d2b3a7bec765127c7/examples/todomvc/containers/App.js#L8

**Comment by gaearon** [comment]
It's important that, the file imports that imports reducers and creates store

* has no side effect
* exports the root React component
* contains `<Provider store={store}>`

**Comment by erikras** [comment]
Hmmm.... That's very interesting. Thanks for clearing that up, @gaearon.

Unfortunately, it's a little hard for me to do, since my middleware that I create the store with needs my api client in order to fetch from both the client and the server. Ideas welcome.

**Comment by erikras** [comment]
@gaearon, can the store be kept *inside* the root React component? That way, I could pass my middleware as a prop and create the store on componentWillMount, or just in the constructor. That feels icky, but that's the only way I can see for me to meet those criteria.

To be honest, I think 95% of the value of the hot reloader is in making layout changes, anyway, so I'm not too terribly disappointed that reducers don't reload in my project, but reloading reducer logic is pretty awesome.

@donabrams I added a counter button to the example, similar to what you had done, for testing this stuff.

**Comment by donabrams** [comment]
Awesome! I was able to get reducer hotswapping working.

I solved this by splitting the top level component into three pieces (formerly in `client.js`). 
1. A `client.js` file that just renders `<ClientApp />` and mounts the component.
2. <`ClientApp>` with it's own `<Provider store={store}>` (store populated from `window`) and the `<DebugPanel>`.
3. `<TopLevelApp>` (that routes based on a url in the store so it's side effect free).

For server rendering, I just wrapped the TopLevelApp with a `<Provider store={store}>`. Still isomorphic when debug is off.

Next for me is data loading just like @erikras was trying to do. I was going to approach it with a similar `EVENT${ '' | 'SUCCESS' | 'FAIL'}` action structure, and I hypothesize as long as this happens in actions and not in the reducer I should be OK.

**Comment by erikras** [comment]
@gaearon & @donabrams Can you see what's wrong with this?
```javascript
import React, {Component} from 'react';
import Router from 'react-router';
import { Provider } from 'react-redux';
import { createStore, combineReducers, applyMiddleware, compose } from 'redux';
import Location from 'react-router/lib/Location';
import BrowserHistory from 'react-router/lib/BrowserHistory';
import routes from './views/routes';
import ApiClient from './ApiClient';
import createMiddleware from './redux/clientMiddleware';
import * as reducers from './reducers/index';

const reducer = combineReducers(reducers);
const location = new Location(document.location.pathname, document.location.search);
const history = new BrowserHistory();
const client = new ApiClient();

const middleware = createMiddleware(client);
const finalCreateStore = applyMiddleware(middleware)(createStore);
const store = finalCreateStore(reducer, window.__data);

export default class ClientApp extends Component {
  render() {
    return (<Provider store={store}>
      {() => <Router location={location} history={history} children={routes}/>}
    </Provider>);
  }
}
```
It renders and works perfectly, but generates the same error as the OP.
```
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
[HMR]  - 374
```
It certainly seems to meet the three conditions @gaearon outlined above.

**Comment by gaearon** [comment]
@erikras Where can I run this?

**Comment by erikras** [comment]
@gaearon [Here's a branch](https://github.com/erikras/react-redux-universal-hot-example/tree/reducer-reload-test).

**Comment by erikras** [comment]
See `ClientApp.js`. For the data loading to work, it'll need to use the middleware, but I've commented it out in desperation.

**Comment by gaearon** [comment]
This is solveable with explicit HMR API call. See here: https://github.com/erikras/react-redux-universal-hot-example/issues/44#issuecomment-132260397.

**Comment by amackintosh** [comment]
This just saved my life in React Native:

> It's important that the file imports that imports reducers and creates store
> 
> - has no side effects
> - exports the root React component
> - contains <Provider store={store}>

If you encounter an error about hot-reloading and what sounds like some kind of deprecation warning, check that you are creating the store `outside` the component that has `<Provider store={store}>` in it.

I was creating the store inside the Root component, so I was clearly offending those rules Mr. Abramov was describing.
