### ISSUE TITLE
NPM install fails on Windows

### ISSUE THREAD

**Issue by jkells** [gaearon/redux-devtools#244]
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! redux-devtools@3.1.1 test: `NODE_ENV=test mocha --compilers js:babel-core/register --recursive`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-devtools@3.1.1 test script 'NODE_ENV=test mocha --compilers js:babel-core/register --recursive'.
npm ERR! This is most likely a problem with the redux-devtools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=test mocha --compilers js:babel-core/register --recursive
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-devtools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\thirdParty\redux-devtools\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! redux-devtools@3.1.1 prepublish: `npm run lint && npm run test && npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-devtools@3.1.1 prepublish script 'npm run lint && npm run test && npm run clean && npm run build'.
npm ERR! This is most likely a problem with the redux-devtools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm run test && npm run clean && npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-devtools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\thirdParty\redux-devtools\npm-debug.log

**Comment by zalmoxisus** [comment]
Changing `"test": "NODE_ENV=test mocha --compilers js:babel-core/register --recursive"` with `"test": "set NODE_ENV=test mocha --compilers js:babel-core/register --recursive"` should help.

We don't check `NODE_ENV=test` anywhere so better to remove it to not stick to specific OS. What do you think, @gaearon?

**Comment by gaearon** [comment]
This is why we use cross-env.

**Comment by Durairaj** [comment]
#322
