### ISSUE TITLE
[Proposal] Move instrumentation to a separate package

### ISSUE THREAD

**Issue by zalmoxisus** [gaearon/redux-devtools#245]
The purpose is not to install React dependencies for [ngrx store](https://github.com/ngrx/store/issues/31) and [remote-redux-devtools](https://github.com/zalmoxisus/remote-redux-devtools). It will also help to avoid issues on React Native like https://github.com/zalmoxisus/remote-redux-devtools/issues/11.

UPDATE: Anyway, we usually want to use `react-redux` on React Native, so probably this will not help avoiding the issue above.

**Comment by jxm262** [comment]
@zalmoxisus  out of curiosity, what sort of naming would you propose for this module (the instrumentor)?  I just recently moved the `persistState` enhancer to a separate module, but not sure I named it well - https://github.com/jxm262/redux-devtools-state-store  

I'd be willing to try and get the Devtools.instrument() logic to a separate module, but do you think their should be some standard naming of these since they're basically all enhancers related to the same thing (devtools) ?

**Comment by zalmoxisus** [comment]
@jxm262, since the proposal was just to move `instrument.js`, this should be `redux-devtools-instrument`. No changes required for this implementation, just we want `redux-devtools` to use this package from outside, otherwise it would be the same as just using our fork without React.

As `ngrx store` is now using its fork of `redux-devtools`, I don't see any interest on this except `remote-redux-devtools`, where the problem is only with React Native and npm<3 getting an exception because of duplicating React.

That said, we need more user cases for splitting it.

**Comment by jxm262** [comment]
@zalmoxisus  thanks for the info.  Waiting for more use-cases sounds like a good plan.

**Comment by gaearon** [comment]
I’m fine with it if you find it useful :+1: 
Would you like to set up the repo?

**Comment by zalmoxisus** [comment]
Will do.

@MikeRyan52, are there still any interest in using the instrumentation inside `@ngrx/devtools`? If so, any requests / suggestions?

**Comment by zalmoxisus** [comment]
@gaearon, implemented in https://github.com/zalmoxisus/redux-devtools-instrument. I mirrored the current repo to keep the information about all the contributions. It has only one dependency - `lodash`. If it looks good to you, I will send a PR for importing it here, and will publish to npm (of course granting you the rights as well).

**Comment by gaearon** [comment]
👍
