### ISSUE TITLE
Access component props in mapDispatchToProps action creator using this

### ISSUE THREAD

**Issue by mauron85** [gaearon/redux-devtools#250]
Assume you have some component and action creator mapped to props via mapDispatchToProps and you need to pass props.id into that action creator. Currently you need to create some handleRemove method, which in turn remove action creator with id from props. But it would be nice if you can call remove action creator without any param and params can be taken from props instead directly.

``` javascript
class CurrentSituationComponent extends Component {
  handleRemove() {
    this.props.remove(this.props.id);
  }
  render() {
    <div onClick={this.props.handleRemove}/>
  }
}

class SuggestedComponent extends Component {
  render() {
    <div onClick={this.props.remove}/>
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    remove: () => {
      dispatch(removeById(this.props.id));
    }
  };
};
const mapStateToProps = (state, ownProps) => {
  const id = ownProps.params.id;

  return {  id };
};

export default connect(mapStateToProps, mapDispatchToProps)(SuggestedComponent);
```

**Comment by gaearon** [comment]
Did you mean to file it in https://github.com/rackt/react-redux instead?
You should already be able to implement this with the optional `ownProps` argument:

```js

const mapDispatchToProps = (dispatch, ownProps) => {
  return {
    remove: () => {
      dispatch(removeById(ownProps.id));
    }
  };
};
```

Note, however, that this will be slower because it will require re-binding the action creators whenever props change.

**Comment by mauron85** [comment]
Ach sorry from wrong repo.

But IMHO ownProps is not solution here as id is coming from state not from passed from parent in form of props.

**Comment by gaearon** [comment]
Wrapping component can’t possible access wrapped component’s state so you have to hoist it up to the parent component.

**Comment by whenov** [comment]
There seems to be two ways to access wrapped component's state in mapDispatchToProps, aside from hoisting it up, you can also use redux-thunk to access getState(). Which do you think is more advisable? @gaearon 

Sorry for replying to this wrongly placed issue.

**Comment by gaearon** [comment]
Both are fine IMO.

**Comment by devssh** [comment]
I was able to hoist it up with a bit of magic without having to create a new component to access the state in mapStateToProps in the mapDispatchToProps. 

```
export default connect(mapStateToProps, mapEmptyDispatchToProps)(connect(mapStateToProps, mapDispatchToProps)(MyComponent));

```

**Comment by devssh** [comment]
Got it working by 

```
connect(mapStateToProps, mapEmptyToProps)(connect(mapStateToProps, mapDispatchToProps)(MyComponent))
```

**Comment by khvr000** [comment]
use mergeProps, read the docs from  
[here](https://react-redux.js.org/api/connect#mergeprops-stateprops-dispatchprops-ownprops-object)
