### ISSUE TITLE
Alternative for float

### ISSUE THREAD

**Issue by 5an1ty** [gaearon/redux-devtools#253]
Currently it seems the DockMonitor floats above my content, making it hard to see my content and still keep the devtools open. Would there be a way to tun the docktools into an object that pushes your content to the side effectively making the content window smaller?

**Comment by gaearon** [comment]
Just remove `DockMonitor` and use `LogMonitor` (or any other monitor) directly :-). `DevTools` you get from `createDevTools` is a regular React component. You can put it anywhere you like.
