### ISSUE TITLE
How to access DockMonitor props from the child monitor reducer?

### ISSUE THREAD

**Issue by romseguy** [gaearon/redux-devtools#255]
Hey,

I'd like to access DockMonitor's `defaultIsVisible` from [`props`](https://github.com/romseguy/redux-devtools-chart-monitor/blob/master/src/reducers.js#L7).

This way I could set `isVisible` default value with it, instead of [`false`](https://github.com/romseguy/redux-devtools-chart-monitor/blob/master/src/reducers.js#L3).

Currently, only `ChartMonitor` element props are passed to `props`, and I'd like to avoid doing something like this:

```javascript
  <DockMonitor
    defaultIsVisible={true}
    {/* other props */}
  >
      <ChartMonitor
        defaultIsVisible={true}
        {/* other props */}
      />
  </DockMonitor>
```

**Comment by gaearon** [comment]
This is on purpose; since they are different monitors unaware of each other they shouldn’t mess with each other’s props. What you suggest is a good enough workaround.
