### ISSUE TITLE
State inspector shows incorrect data if opened after redux-thunk promise is fulfilled

### ISSUE THREAD

**Issue by samphilipd** [gaearon/redux-devtools#261]
I am using redux-thunk middleware to perform asynchronous dispatches.

In my simple example I add a message to the store with a 'PENDING' state, then post to the server. Based on the server response we mark the message 'RECEIVED' or 'REJECTED'.

The action looks like this:

```jsx
export const sendMessage = (author, body, submitTime = new Date) =>
  dispatch => {
    const messageLocalId = localId++;
    dispatch(addMessage(author, body, submitTime, messageLocalId));

    return request({
      method: 'POST',
      url: '/api/message.json',
      responseType: 'json',
      headers: {
        'X-CSRF-Token': getCSRFToken(),
      },
      data: {
        message: { author, body, sent_at: submitTime.toISOString() },
      },
    }).then(res => {
      const canonicalId = res.data.message.id;
      dispatch(serverReceivedMessage(messageLocalId, canonicalId));
    }).catch(err => {
      dispatch(serverRejectedMessage(messageLocalId))
    });
  };
```

If I execute the action and delay processing of the server (using e.g. a 30s sleep) the first dispatch is called, and if I check the state with the inspector is shows the correct 'PENDING' status. This is before the promise is fulfilled.

However, if I wait until after the promise is fulfilled and THEN inspect the state object for the first action, it incorrectly shows the new message having state 'RECEIVED' even though this isn't the case.

So to be clear, there are TWO actions here - ADD_MESSAGE and RECEIVED_MESSAGE. If I inspect the state of ADD_MESSAGE **before** the promise is fulfilled then it appears correctly. If I inspect the state of ADD_MESSAGE **after** the promise is fulfilled then it incorrectly reports the state as it is after RECEIVED_MESSAGE, not as it should be after ADD_MESSAGE.

If you need more code to help debug this please let me know.

**Comment by zalmoxisus** [comment]
Hey @samphilipd,

Thanks a lot for reporting this! I'm not sure this is directly related to `redux-devtools`. Does this happen only when adding DevTools enhancer to your store? Try without Redux DevTools, using `redux-logger` middleware or just to check it you could expose the store globally (`window.store = store`) in the `configureStore`, and then in the console compare what you get from `store.getState()`.

If it is really Redux DevTools changing the real state, then it would be very useful, I think, to have a [test here](https://github.com/gaearon/redux-devtools/blob/master/test/instrument.spec.js) for asynchronous requests, where you would mock the API with a 30s timeout. So, we'll be able to investigate it.

**Comment by samphilipd** [comment]
@zalmoxisus turns out this is **not** any problem with DevTools and was actually my fault. I accidentally mutated the object using `Object.assign` incorrectly :smile: .

Feel free to close this issue, and thanks for the fantastic debugging tool!

**Comment by zalmoxisus** [comment]
@samphilipd, you're welcome. Use `redux-immutable-state-invariant` to prevent such situations.

**Comment by samphilipd** [comment]
Actually I just moved everything to Immutable.js
