### ISSUE TITLE
Support for Immutable.js Not Work Again

### ISSUE THREAD

**Issue by lcxfs1991** [gaearon/redux-devtools#265]
I recently upgrade to latest redux-devtools, dock and log panel, then I found this. (also latest react 15.0.0, redux and immutable):

I then resolve it by using tips from this issue: 
https://github.com/gaearon/redux-devtools/issues/51

I think you have solved this problem at certain version. Could you please check if it is related to new react/redux update?

**Comment by granmoe** [comment]
I'm having the issue, too. Can you share the workaround? I looked at the issue you linked, but I am very new to redux-devtools and it looks like the API has changed drastically from 1.x. I'm not sure how to implement it.

**Comment by gaearon** [comment]
Mind looking into why this happens?

**Comment by lcxfs1991** [comment]
![qq 20160408160025](https://cloud.githubusercontent.com/assets/3348398/14401124/e4bd150c-fe38-11e5-88a5-4b90a7f60b42.png)

add a screenshot

**Comment by gaearon** [comment]
I don't understand what this screenshot means. Can you please clarify?

Can you find why the issue happens and which exactly update broke the support? It is not clear from the issue report.

**Comment by lcxfs1991** [comment]
Usually, the tree will display like this:
state
   |
   setLoading: false

I try to use toJS method for immutable object in node_modules and then it works. 

I will also dig into it later in the day. I am in a rush for a project.

**Comment by gaearon** [comment]
Maybe @alexkuz has any ideas

**Comment by lcxfs1991** [comment]
just add your Facebook.  Actually strongly recommend Facebook building up stronger control over these tools, or offering an official tookits.

**Comment by granmoe** [comment]
I cloned redux-devtools and npm linked it in my project. I then checked out a version that I know was working with immutable.js, rebuilt and ran my project, and it still didn't work. I'm wondering if some other package is to be blame. The problem first manifested when I upgraded a bunch of packages at once, so I'll try decrement those packages back one by one and report back.

**Comment by alexkuz** [comment]
This is probably related to [react-json-tree](https://github.com/alexkuz/react-json-tree) (there were some fixes for immutables), so it's better to create an issue there or at [redux-devtools-log-monitor](https://github.com/gaearon/redux-devtools-log-monitor).

**Comment by gaearon** [comment]
This is most likely react-json-tree issue. Please check if it works with Immutable and if something broke please file it there. I'm closing because there is nothing specially actionable for us in this repo.

**Comment by granmoe** [comment]
For anyone who lands here from a search, I found the bad commit in react-json-tree using git bisect and opened an issue there: https://github.com/alexkuz/react-json-tree/issues/45
