### ISSUE TITLE
Distracting console.log statement

### ISSUE THREAD

**Issue by ffxsam** [gaearon/redux-devtools#268]
I've suddenly started seeing this in my console:

    maxAge 50 2

I believe this is coming from redux-devtools somewhere, though I'm not 100% sure as I can only see minified code.

**Comment by ffxsam** [comment]
PS: I'm using the Chrome extension

**Comment by gaearon** [comment]
>PS: I'm using the Chrome extension

That’s where it’s coming from, and it’s been fixed there so an update should be available soon.
