### ISSUE TITLE
Don't catch errors?

### ISSUE THREAD

**Issue by DelvarWorld** [gaearon/redux-devtools#269]
This might be more of a suggestion or personal preference, but what is the motivation for catching errors produced by actions? https://github.com/gaearon/redux-devtools/blob/master/src/instrument.js#L78-L80

This means if an action causes an error in *any* other part of my application, like a component remounting, then the error will be caught, the stack trace lost, and then error in a different place.

This makes it more difficult to find errors in dev. It also means that the "pause on exceptions" setting can't be used without "pause on uncaught exceptions" - which, if on app startup (page refresh), means you have to step through about 30 babel/webpack intentionally caught errors to see the error in question.

For me personally it would be nicer for local app development and debugging if error stack traces were preserved.

**Comment by zalmoxisus** [comment]
Hey @DelvarWorld,

The purpose is to see which action (reducer) caused the error. The stack trace shouldn't be lost, at least in Chrome:
![b3uspjmfdk](https://cloud.githubusercontent.com/assets/7957859/14602645/b0b4eef2-0571-11e6-9c7c-cf1e5ec8f6e4.gif)

**Comment by gaearon** [comment]
>This means if an action causes an error in any other part of my application, like a component remounting, then the error will be caught, the stack trace lost, and then error in a different place.

This is not correct. Only reducer is guarded with `try`/`catch`. Components (which are subscribers and are called after the reducer) will have their error thrown normally.

And yea, stack traces should be working fine.

**Comment by DelvarWorld** [comment]
Oh, whoops! I wasn't seeing a stack trace but that's because I had my own `.catch()` promise code buried in there. Nothing to see here.

**Comment by naw** [comment]
Catching errors has the subtle side effect of changing the API that `dispatch` exposes from the perspective of the caller, and thereby changing the observed behavior of the application.

_Without_ DevTools, `dispatch` can throw an error, which will bubble up and (presumably) be handled higher in the stack frame by the application, or handled indirectly via a rejected promise, etc.

_With_ DevTools, `dispatch` never throws an error (or in Chrome, throws an error in the next tick), which means the application itself (may) can't catch it. Therefore, the behavior of the application can actually change just by adding DevTools. 

@gaearon would you be open to this aspect of DevTools being configurable?
