### ISSUE TITLE
Devtools seem to break reduxs observable support

### ISSUE THREAD

**Issue by micha149** [gaearon/redux-devtools#274]
Redux implemented support for observables since v3.5.0. When I attach an observable to the store, I will receive the devtools state instead of my application state.

A quick example:

```javascript
import {Observable} from 'rxjs';
import {createStore, compose, applyMiddleware} from 'redux';
import thunk from 'redux-thunk';

const store = createStore(rootReducer, compose(
    applyMiddleware(thunk),
    window["devToolsExtension"] ? window["devToolsExtension"]() : f => f
));

Observable.from(store).map(state => console.log(state));
```

Will log something like `Object {monitorState: Object, actionsById: Object, nextActionId: 1, stagedActionIds: Array[1], skippedActionIds: Array[0]…}` when the store updates.

When I disable the redux devtools in Chrome, I get the expected state instance.

**Comment by gaearon** [comment]
Out in 3.3.0.
