### ISSUE TITLE
Suggestion: customisable storage for persistState()

### ISSUE THREAD

**Issue by crobi** [gaearon/redux-devtools#276]
`persistState` is hardcoded to write to localStorage under the key `redux-dev-session-${sessionId}`.

It would be nice if I was able to use a custom database for `persistState`. In particular, I want to use a remote server to make sharing debug sessions easier (can't find the bug? just send the session hash to your coworker).

- Serializing and deserializing the state would become async. The lifted store reducer would probably need to use `redux-thunk` or a similar library, and it might introduce new actions.
  - Those new actions might be useful for the devtools anyway. E.g., instead of `console.warn('Could not read debug session')`, you could emit a `STATE_RESTORE_FAILED` and let some UI component display a nice warning.
- Maybe add support for the session id to be generated (in my use case, the key for each session would be auto-generated by the server as the sha256 hash of the serialized session string)

```ts
// Default storage
function writeLocal(sessionIdHint: string, state: any): Promise<sessionId> {
    try {
        localStorage.setItem(sessionIdHint, JSON.stringify(state));
        return Promise.resolve(sessionIdHint);
    } catch (e) {
        return Promise.reject('Could not write debug session to localStorage:');
    }
}
```

```ts
// Remote storage
function writeRemote(sessionIdHint: string, state: any): Promise<sessionId> {
    return fetch(`${serverURL}/json/$(sessionIdHint)`, {
        method: "POST",
        body: JSON.stringify(state),
        headers: {
            "content-type": "application/json"
        }
    })
    .then(response => response.json())
    .then(data => data.hash /* server response contains the auto-generated key */);
}
```

**Comment by zalmoxisus** [comment]
Hey @crobi,

What you want to accomplish here, I've already implemented in [Remote Redux DevTools](https://github.com/zalmoxisus/remote-redux-devtools), including the monitor app supporting multiple instances and the remote server.

Also, a possible solution was implemented [here](https://github.com/gaearon/redux-devtools-log-monitor/pull/46).

Anyway, you can add this functionality easily by just using a `store.subcribe(() => { sendToServer(store.liftedStore.getState) })` and `function importFromServer() {  store.liftedStore.dispatch({ type: 'IMPORT_STATE', nextLiftedState: stateFromServerToImport }) }`.

**Comment by crobi** [comment]
Thanks for the info! I didn't know about Remote Redux DevTools, shame it's not listed from the Redux project readme. I am going to use your suggestion with using  `IMPORT_STATE`, this is exactly what I need.
