### ISSUE TITLE
Import State using seamless-immutable

### ISSUE THREAD

**Issue by gschwa** [gaearon/redux-devtools#277]
I have built a  custom import/export monitor which allows my team to capture the state as a string to be included into bug reports and then to allow developers to apply the state in order to reproduce the bug. It works great except when starting with a committed state. We are using seamless-immutable so when the state is imported I need to be able to post process the state to make it Immutable. Are there any hooks to make this possible? Any suggestions?

**Comment by zalmoxisus** [comment]
Hey, @gschwa. Before dispatching `{ type: ActionTypes.IMPORT_STATE, liftedState }`, you can preprocess `liftedState.computedStates` array like we do for `persistState` [here](https://github.com/gaearon/redux-devtools/blob/master/src/persistState.js#L17-L20).

Please let me know if it helps as I want  to solve https://github.com/zalmoxisus/redux-devtools-extension/issues/100 and not sure yet whether to implement it on the extension part or in the instrumentation enhancer.

**Comment by gschwa** [comment]
@zalmoxisus that did not solve the problem because in https://github.com/gaearon/redux-devtools/blob/master/src/instrument.js#L99 the `computedStates` is basically ignored and recalculated into `nextComputedStates`. Any chance there is a hook to post-process?

**Comment by zalmoxisus** [comment]
Closing as being addressed in https://github.com/zalmoxisus/redux-devtools-instrument/issues/3.

An example of implementation can be found in https://github.com/zalmoxisus/redux-devtools-extension/commit/3a3185fc857aaabd599f32e72e2d7a47bf2504e2.
