### ISSUE TITLE
Instrument enhancer allows dispatching non-plain objects

### ISSUE THREAD

**Issue by alexanderchr** [gaearon/redux-devtools#278]
Redux [prohibits](https://github.com/reactjs/redux/blob/master/src/createStore.js#L150) dispatching non-plain objects. But with the instrument enhancer enabled it's possible to do so. This makes it easy to accidentally write code that works in development but crashes in production, which is really not that good.

Not sure what would be the best way to solve this. We could of course add the same checks as in redux, but then we'd have to be sure to keep them in sync with redux.

**Comment by zalmoxisus** [comment]
Should be fixed in https://github.com/zalmoxisus/redux-devtools-instrument/commit/d2546f89aaf26a1de7757b8e599c4907c375388f

**Comment by alexanderchr** [comment]
Thank you!
