### ISSUE TITLE
"toObject is not a function" with persistState and Immutable data 

### ISSUE THREAD

**Issue by philholden** [gaearon/redux-devtools#28]
When I use `persistState` and with a debug session and immutable data I get the error below when I reload the page after committing:

```
Uncaught TypeError: campaign.toObject is not a function
```

My state is an immutable record.

```javascript
const table = Record({
  rows: List([]),
  sortBy: 'name',
  isAsc: false,
  mode: ACTIVE
});
```

Are there any hooks I can use to turn persisted state back into an immutable record

**Comment by philholden** [comment]
Ok solved it added toImmutable in my reducer it checks if the current state is a Record and if not converts it to one. 

```javascript
function toImmutable(state) {
  if (state instanceof Record) {
    return state;
  } else {
    state.rows = List(state.rows);
    return new Table(state);
  }
}

export default function (state = initialState, action) {
  state = toImmutable(state);
  switch (action.type) {
```

**Comment by gaearon** [comment]
Yeah that's how I'd do it too.
