### ISSUE TITLE
Does the latest redux-devtools fully work with Immutable JS?

### ISSUE THREAD

**Issue by jasan-s** [gaearon/redux-devtools#283]
I have been using POJO pattern with spread operators (...)thus far with redux store, however i want to  start using Immutable js, but Just want to know if redux-devtools or any other great Redux addons don't collaborate well with it. ( more of a discussion than a issue)

**Comment by zalmoxisus** [comment]
As long as you don't have top level immutable state, there shouldn't be any problems.

**Comment by hamishtaplin** [comment]
Sorry to hijack this but is there any scope to be able to debug immutable constructs from within the devtools? For example, it would be good to be able to see what the type (Map, List, etc) of a particular bit of state is. This would highlight any bits of state that _aren't_ immutable, helping to catch problems early.

**Comment by zalmoxisus** [comment]
@hamishtaplin, in [`redux-devtools-extension`](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md) you can customize how the data are serialized. For example you can add one additional parametter which will show the data type:

```js
const store = Redux.createStore(reducer, window.devToolsExtension && window.devToolsExtension({
  serializeState: (key, value) => (
    value && Map.isMap(value) ? { ...value.toJS(), dataType: 'map' } : value
  )
}));
```

It's just a simple object you could add a switch to check every type. Also we're planning to specify styles for specific data in state (for example if there's an `error` key). This additional parameter will not be added to your real store, just for the monitor to be displayed.

If you could come with a final solution, it would be helpful, we'll add it to the recipes.

**Comment by hamishtaplin** [comment]
@zalmoxisus Thanks, I'll check that out.

**Comment by zalmoxisus** [comment]
Redux DevTools Extension got full support for ImmutableJS out of the box, just pass the Immutable library in `serialize` parameter. See [the release notes](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.12.1) for more details.
