### ISSUE TITLE
multi standalone redux application in the same page

### ISSUE THREAD

**Issue by lior-a** [gaearon/redux-devtools#284]
Hey,

so I have more than one application within the page but sadly I can debug just one at a time and the only way for me to do so is to kill the other one.

Is there a feature that can toggle the two that I am missing? or there is other way to debug both application?

Thanks for the help

**Comment by zalmoxisus** [comment]
Theoretically, you can specify stores by adding to DevTools props and [opening them in new windows](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#or-open-them-in-a-new-window). Another option would be to use [Remote Redux DevTools](https://github.com/zalmoxisus/remote-redux-devtools), where you can name every instance and easily switch between them.

**Comment by lior-a** [comment]
how do you specify stores? and i tried to open Devtool in new window but it doesn't show all app stores that within the page(but does show app stores that in another page)

* I am using the chrome extension.

**Comment by zalmoxisus** [comment]
The extension will not work for multiple stores in one page as we're using tab id as the instance id there, as the result the latest store overrides everything else. In contrast [Remote Redux DevTools](https://github.com/zalmoxisus/remote-redux-devtools) creates a new connection for every store, an you'll get all the instances there.

**Comment by zalmoxisus** [comment]
Starting from `2.0` the extension [supports multiple stores in one page](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.0.0).
