### ISSUE TITLE
redux-devtools for ux analysis

### ISSUE THREAD

**Issue by ChrisFan** [gaearon/redux-devtools#288]
The traditional way for ux analysis is:

1. make an extra ajax request when user click some specified elements
2. analyse those data, sometimes draw a heap map or maybe reproduce the user behavior

And now with redux:

1. we could save actions with the redux store instead of those click events
2. we could replay user actions and do data analysis based on actions

Dose anybody tried this before ?
Currently the problem seems to be that the store & actions data are a bit large.

> This may not a be a user case for redux-devtools but the idea is quite related to redux-devtools.

**Comment by zalmoxisus** [comment]
@ChrisFan, yes, [Remote Redux DevTools](https://github.com/zalmoxisus/remote-redux-devtools) was created exactly for that.

**Comment by ChrisFan** [comment]
@zalmoxisus , It's awesome, and is quite useful for ux analysis in development.

I'd like to move one step further, use it in production, but the thing is if we store all the data of actions, it's definitely too much for our server.

**Comment by zalmoxisus** [comment]
@ChrisFan, we'll add there [filter functions](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v1.4.0) a bit later, want to test more thoroughly with the extension.

**Comment by ChrisFan** [comment]
@zalmoxisus, cool & thx.
