### ISSUE TITLE
Debugging Session is not re-hydrating state

### ISSUE THREAD

**Issue by michael-iglesias** [gaearon/redux-devtools#289]
I've included all of the boilerplate code included in the walkthrough. Devtools is working fine with the exception of re-hydrating state when I access the following url...
"localhost:8080/?debug_session=reproducing_weird_bug"

App state is in fact being stored in localStorage with a key of 
"redux-dev-session-reproducing_weird_bug". 

When I change my app state in localStorage:
      ("redux-dev-session-reproducing_weird_bug", "count: 1") 
after refreshing the page it defaults back to:
      ("redux-dev-session-reproducing_weird_bug", "count: 0")

Any ideas on why my app state is being set to initalState and not re-hydrating from localStorage?

Thanks in advance,
Michael I.

**Comment by zalmoxisus** [comment]
Most likely you forgot to apply `persistState` enhancer as indicated [here](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#use-devtoolsinstrument-store-enhancer).
