### ISSUE TITLE
Actions from the dispatcher tab skip saga middleware

### ISSUE THREAD

**Issue by parkerbossier** [gaearon/redux-devtools#290]
If I dispatch { type: 'Page/FETCH' } in the dev tools dispatcher, it goes straight to the reducer. If, however, I dispatch the same action on the store directly, the saga middleware will pick it up. Here's my store initialization:

const enhancers = Redux.compose(
	Redux.applyMiddleware(sagaMiddleware),
	(window as any).devToolsExtension ? (window as any).devToolsExtension() : f => f
);
const store = Redux.createStore(reducer, initialState, enhancers);

sagaMiddleware.run(function* () {
	yield* mySaga(store.getState);
});

If I put dev tools before the saga middleware, the store appears to be oblivious of all actions. Is this a fundamental limitation?

**Comment by croemmich** [comment]
I have the same issue. Actions are picked up by my reducers, but not sagas. Dispatching programmatically works as expected.

**Comment by zalmoxisus** [comment]
Addressed in https://github.com/zalmoxisus/redux-devtools-extension/issues/133. It should work now, if you build the extension from github as described there. After more testing will publish the fix to Chrome store. Please discuss the extension on its repository.
