### ISSUE TITLE
Replacing reducer on store makes Devtools replays all actions from beginning

### ISSUE THREAD

**Issue by yachaka** [gaearon/redux-devtools#291]
I've been noticing that replacing the reducer on the store dispatch an `@@INIT` action.
When combined with `redux-devtools` or `redux-devtools-extension`, it seems to be replaying all actions since beginning each time you replace the reducer.

Fast recipe to reproduce :

1. `git clone https://github.com/mxstbr/react-boilerplate.git && cd react-boilerplate && npm install`
2. Install [redux-devtools-extension](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd)
3. Add `console.log('Reducer called', action)` at the start of `appReducer` in `~/app/containers/App/reducer.js` 
3. Open console, go to `http://localhost:3000`, move back and forth between the Features and the Home page, and watch the log output

Mind that the replay will only occur when going to the Home page and not when going to the Features page. This is due to the fact that the Features page is not injecting a reducer, and so not replacing the store's reducer, while the Home page is.

**Comment by yachaka** [comment]
I'm digging a little bit into the `redux-devtools-instrument` code right now.
It seems like the actions only gets re-reduced. It isn't a concern then, though it is a little bit weird as they only get re-reduced in the tool.

**Comment by zalmoxisus** [comment]
@yachaka, the purpose of the recomputing is to get new values after you change something in the reducers. See more details in [Dan's talk](https://youtu.be/xsSnOQynTHs).

Also, reducers are called when you toggle (cancel) an action down the history tree.

**Comment by zalmoxisus** [comment]
Related to #304.
