### ISSUE TITLE
Minified Exception Occurred

### ISSUE THREAD

**Issue by faurehu** [gaearon/redux-devtools#292]
Redux Devtools was working just fine but I changed environments recently and haven't managed to get it running ever since. I am using the Chrome extension and I get the following message in the Redux pane:

`Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.`

All instances I have found of this error are strictly related to React. This is supposed to happen when the build minifies the scripts, but my webpack config is not minifying anything. I have checked the sources myself and everything looks complete.

**Comment by zalmoxisus** [comment]
The extension is not minified, and also it doesn't include React. So, the exception should be thrown from elsewhere. If not, please provide more details to reproduce the issue.

**Comment by faurehu** [comment]
@zalmoxisus the only details I can think of that I didn't already mention would be that the application is being served with webpack-dev-server. I didn't set the application myself but I did add the Redux devtool.  Please let me know what else I could inspect for you so I can reply with the details.

**Comment by zalmoxisus** [comment]
@faurehu, it is not related to your webpack config, as the extension is already built with minified react. Can you replicate it with [our examples](https://github.com/zalmoxisus/redux-devtools-extension#demo)? If not, please provide an example project, so I could replicate it. Or you can [run the extension in the dev mode](https://github.com/zalmoxisus/redux-devtools-extension#1-get-the-extension), so you'll be able to debug it.

@danilotorrisi, you mean chrome extension as well, right? Or you have the same problem using vanilla redux-devtools? If so, which monitor do you use?

**Comment by faurehu** [comment]
@zalmoxisus I couldn't share a sample project since the one I'm working on is massive and proprietary. I decided to try to debug it myself so I ran the extension in dev mode like you suggested. However, the dev build works just fine. I tried reinstalling from the Chrome Web Store but the minified exception occurred again. I'm sorry I can't provide more information for you to reproduce.

**Comment by zalmoxisus** [comment]
@faurehu, it could be an issue of React itself then. Or maybe you installed different version of React or Inspector monitor (the major one). Maybe try to [build the extension](https://github.com/zalmoxisus/redux-devtools-extension#1-get-the-extension) (not in dev mode) and try different versions of React.

**Comment by zalmoxisus** [comment]
I just published `v2.0.2` on Chrome store with updated react and `remotedev-app`. Could you please give it a try?

**Comment by faurehu** [comment]
Just tried, same issue. However, if I launch the devtool from the Chrome menu bar, it works alright. I don't know if that was working properly when I first wrote this issue (I hadn't tried). Using the Chrome developer tool panels still shows the same message though.

**Comment by danilotorrisi** [comment]
@zalmoxisus I'm using vanilla redux-devtools but it was totally my fault, wrong webpack configuration merged from another branch, sorry for bothering you!

**Comment by zalmoxisus** [comment]
@faurehu, in `v2.1.0` I included the full stack trace along with the error message in Chrome Devtools panel.  Maybe that could help to identify the problem.
