### ISSUE TITLE
Provide a way to change or disable keyboard shortcuts

### ISSUE THREAD

**Issue by mattbroussard** [gaearon/redux-devtools#293]
I find that I have to disable the extension in order to use the `cmd-ctrl-up` shortcut on Dropbox Paper, otherwise the extension catches the event and opens its popup window.

It would be nice to change the shortcut, or disable the keyboard shortcuts entirely.

**Comment by zalmoxisus** [comment]
On the bottom of `chrome://extensions/` page there's a "Keyboard shortcuts" link where you can customize the extension's shortcuts.

Please address the issues related to the extension on [its repository](https://github.com/zalmoxisus/redux-devtools-extension).

**Comment by mattbroussard** [comment]
Thanks! I didn't realize that was there.

**Comment by zalmoxisus** [comment]
@mattbroussard, you're welcome. I've added the information about this in https://github.com/zalmoxisus/redux-devtools-extension/commit/83455a1cf832e6e6f61fb7d47df83cee1b371a2c.

**Comment by CPCer** [comment]
Thank you thank you Mr.Zalmoxisus! It does make me feel great to get rid of the annoying keyboard shortcuts of `Save Page WE`, which gives no info about how to disable
