### ISSUE TITLE
It's difficult to correlate Slide Monitor to state and actions

### ISSUE THREAD

**Issue by jrullmann** [gaearon/redux-devtools#295]
I've been trying to use the Slide Monitor to debug. For example, I can slide backwards to find when a problem first occurred in my application.

Once I determine when a problem was introduced, I then want to see the current state of the store and also the actions that had been dispatched up to that point. That way I can figure out what went wrong - was something dispatched with a weird payload? Was there something already in the store that, when combined with the last dispatch, resulted in weird data? That kind of thing.

However, when I use Slide Monitor I can see my application changing, but I can't see the current state of the store or the dispatched actions. If I could correlate these things it would be amaaazing.

I use Slide Monitor and Log Monitor at the same time. I had expected that, when I change the slider, actions in the Log Monitor would be disabled. But it seems like it was an intentional decision not to support this behavior (https://github.com/gaearon/redux-devtools/pull/5).

Hopefully we can think about ways to make this correlation possible.

**Comment by zalmoxisus** [comment]
It would be great indeed to indicate that in Log and Inspector Monitor by changing the style for the actions which are in "the future".

**Comment by zalmoxisus** [comment]
Implemented in https://github.com/gaearon/redux-devtools-log-monitor/pull/56. Let's continue the discussion there.

**Comment by zalmoxisus** [comment]
Update: It works in the extension for Log Monitor.
