### ISSUE TITLE
Empty in dev panel and in "pop-up" with error : Uncaught Error: Cannot find module "./A

### ISSUE THREAD

**Issue by loic294** [gaearon/redux-devtools#296]
The redux dev tool was working perfectly and it just stopped working. I have version 2.2.0.2 When I inspect the Redux DevTools I get this error: 

```
window.bundle.js:20095 Uncaught Error: Cannot find module "./App"
```

There is nothing in the stack trace...

![2016-06-29 1](https://cloud.githubusercontent.com/assets/1829117/16441129/c12c0ff2-3d95-11e6-8881-42e78c0f9165.png)

![2016-06-29 3](https://cloud.githubusercontent.com/assets/1829117/16441189/533d3e0c-3d96-11e6-9f4e-1812c6286ce7.png)

**Comment by tedscape** [comment]
+1 Facing the same issue.

**Comment by buckyroberts** [comment]
I am having the same issue. There must be a bug in the new version.

**Comment by nothinkelse** [comment]
I have blank Redux tab in 2.2.0.2 as well. Works fine on my other chrome where I still have 2.2.0.1 of Redux. How can I get back to 2.2.0.1?

**Comment by zalmoxisus** [comment]
Fixed in https://github.com/zalmoxisus/redux-devtools-extension/pull/151, please update the extension to `2.2.0.3`. Please refer to https://github.com/zalmoxisus/redux-devtools-extension/issues/150 if there are any other problems.
