### ISSUE TITLE
persist state filling up local storage very quickly

### ISSUE THREAD

**Issue by tnrich** [gaearon/redux-devtools#298]
Hey there,

I have a fairly large redux store, and my chrome debugger gets full quite quickly resulting in this message: 

```
Could not write debug session to localStorage: DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'redux-dev-session-1' exceeded the quota.(…)"
```

Does anyone know of a good way of dealing with this issue? Can localStorage be auto-cleared if it fills up? Maybe there could also be an option to have persistState only send a smaller portion of the action history if the redux store is above some threshold?

Any help would be appreciated!

**Comment by zalmoxisus** [comment]
Well, it depends on the browser preference and disk space. What you want to do is to whether click `Commit` button on log monitor every time to clear the history or even better to limit the history by adding [`maxAge` parameter](https://github.com/zalmoxisus/redux-devtools-instrument#api) as following:
```js
const enhancer = compose(
  applyMiddleware(d1, d2, d3),
  DevTools.instrument({ maxAge: 50 })
);
```

**Comment by tnrich** [comment]
Sweet thanks for the maxAge tip!

**Comment by tnrich** [comment]
A follow up question: I would like to blacklist some of the reducers from being persisted. Is that possible to do with persistState? Or should I look at a different implementation of persistState to do that?

**Comment by tnrich** [comment]
@zalmoxisus @gaearon ?

**Comment by tnrich** [comment]
I'm still unfortunately hitting this issue much more often than I'd like (often after changing pages through redux-router). Is there something else I should look into for fixing this issue?

**Comment by zalmoxisus** [comment]
When the persisted lifted state is loaded, the reducers are recomputed with those values. Not having all the data, will cause unexpected results.

However, if you want to filter some data you can add a store enhancer as following:
```js
const persistSelector = createStore => (reducer, preloadedState, enhancer) => {
  const store = createStore(reducer, preloadedState, enhancer);
  const getState = store.getState;
  store.getState = () => {
    const liftedState = getState();
    // Here you can filter what to be persisted
    return liftedState;
  };
  return store;
};
```

Then apply it:
```js
const enhancer = compose(
  applyMiddleware(thunk),
  DevTools.instrument(),
  persistSelector,
  persistState(
    window.location.href.match(
      /[?&]debug_session=([^&#]+)\b/
    )
  )
);
```

In `3.0` version of Redux DevTools Extension it will be possible to save and load a state history (locally or remotely). For now, you can use `Export` / `Import` button there, which would solve the `localStorage` issues.

**Comment by tnrich** [comment]
Hey @zalmoxisus , thanks for the tips! When do you think version 3.0 will drop?

**Comment by zalmoxisus** [comment]
@tnrich, I'd like to have it at the end of the year, but cannot guarantee yet.

**Comment by zalmoxisus** [comment]
Hey @tnrich, I'm still not ready for `3.0`, but I went ahead and made [a PR for addressing this issue](https://github.com/zalmoxisus/redux-devtools-extension/pull/276). I'll publish `2.12` these days along with other changes.

**Comment by tnrich** [comment]
That's great to hear. Thanks!
