### ISSUE TITLE
Hot reloading doesn't work fine for components in the examples

### ISSUE THREAD

**Issue by gabrielmicko** [gaearon/redux-devtools#301]
**When I change any component and hit save, the refresh happens, but I can't see the change. The WebSocket traffic says type:invalid.**

"react-hot-loader": "^3.0.0-beta.1",

Uploading a video.
[redux-devtools-todo-bug.zip](https://github.com/gaearon/redux-devtools/files/356075/redux-devtools-todo-bug.zip)

Is it a bug?

**Comment by gabrielmicko** [comment]
I tried to checkout to 25eab605621ea3f46921f2751b1538dd2afb528c commit and it works.

**Comment by rajeshaz09** [comment]
My last  commit caused this issue. created new pull request. https://github.com/gaearon/redux-devtools/pull/303

**Comment by gabrielmicko** [comment]
@rajeshaz09  thank you!

**Comment by zalmoxisus** [comment]
Fixed in https://github.com/gaearon/redux-devtools/commit/619a18b26a5482585b10eddd331ccacf582ba913
