### ISSUE TITLE
Unfriendly errors when trying to access undefined

### ISSUE THREAD

**Issue by woniesong92** [gaearon/redux-devtools#302]
<img width="645" alt="screen shot 2016-07-10 at 9 51 55 am" src="https://cloud.githubusercontent.com/assets/2935309/16714906/d0140d8c-4685-11e6-83b3-b8be57e86291.png">

You get the errors above if you try to do anything like this inside a component's `render()`:

```javacsript
render() {
  const { name, age } = this.props.person // person object only contains `name` key
}
```

You can also reproduce the same error if you thought you imported something valid, but end up accessing `undefined`.

Is there a way to get more useful errors like `age doesn't exist in undefined`?
I thought using the latest `react-hot-loader` would solve the problem, but I might have been mistaken as I still see those unfriendly errors.

**Comment by zalmoxisus** [comment]
Thanks for the report, but I don't see how it's related to this repository (to Redux Devtools). Probably you want to address it to `react-hot-loader` repository.
