### ISSUE TITLE
Suggestion: Add possibility to see specified attributes in action listing

### ISSUE THREAD

**Issue by jurosh** [gaearon/redux-devtools#307]
Hi guys, while working with great :+1:  redux devtools I realized that one feature (not so complex) may be interesting to add. So please let me know what do you think.

In devtools listing of actions we see only type of action - what is cool, but what if we want to see also some important attribute. See following example:

We have actions like `EXPAND_ITEM` with attribute `id`, then eg. `OPEN_ITEM` etc.. and would be nice if we may like pin that `id` attibute to action name (type).

Current output:
```
EXPAND_ITEM
OPEN_ITEM
FETCH_SUCCESS
```
Nicer output (with some pinned attributes):
```
EXPAND_ITEM (id: 123)
OPEN_ITEM (id: 123)
FETCH_SUCCESS (id: 'articles')
```
or
```
EXPAND_ITEM:123
OPEN_ITEM:123
FETCH_SUCCESS:articles
```

So it may looks like this:
![Preview](https://screen.jurosh.com/i15/2016_07_25_58699192152037006.png)

Result would be that we don't need to click on action to see some basic identifiers/attributes which are not in type directly - so we may debug some more generic actions nicer.
It may work also with more pinned attributes and it may show only those which are not undefined.

So question is what do you think, and if it's possible that someone would be interested in implementing functionality like this ?

**Comment by zalmoxisus** [comment]
Well, according to the screenshot, this suggestion is related to [`redux-devtools-inspector`](https://github.com/alexkuz/redux-devtools-inspector) and should be addressed there. But we have something similar already implemented in [`redux-devtools-log-monitor`](https://github.com/gaearon/redux-devtools-log-monitor), so you can use it. Actually hiding details in tabs was one of the reason of creating `redux-devtools-inspector`, as actions payloads can be too large and it will affect the performance. Though pinning attributes is a nice idea, and would be a rather useful contribution [there](https://github.com/alexkuz/redux-devtools-inspector). If you need more details in how to create a PR, let me know, I'd be happy to help.
