### ISSUE TITLE
Using export/import on Chrome Ext with Immutable.js as state doesn't work

### ISSUE THREAD

**Issue by alisman** [gaearon/redux-devtools#308]

**Comment by alisman** [comment]
When I export my store, it gets outputted as pojo.   When I try to import, reducers throw error b/c state is not Immutable.  Anything to be done?

**Comment by zalmoxisus** [comment]
@alisman, yes, you need to deserilize the state. There's more details and an example in the [docs](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#windowdevtoolsextensionconfig). If you still experience problems with that, please open an issue on the [extension's repo](https://github.com/zalmoxisus/redux-devtools-extension).
