### ISSUE TITLE
Doesn't seem to work with Set objects

### ISSUE THREAD

**Issue by jameskraus** [gaearon/redux-devtools#310]
Hey, I was using redux-devtools-extension and it didn't seem to accurately report the contents of my state if the state contained a Set object. For example, if I set the state to 

`{
  mySet: new Set(['1','2','3'])
}`

the tool seems to think the state is

`{
  mySet: {} 0 keys
}`

I'm using chrome 52 and just using console.log(state), it seems that my browser does understand the state to contain the Set object, so I don't think it's a browser issue.

**Comment by zalmoxisus** [comment]
The browser does understand it, but `JSON.stringify` not.
Import [`set.prototype.tojson`](https://www.npmjs.com/package/set.prototype.tojson) to get it work. Also see [the discussion about `Map`](https://github.com/zalmoxisus/redux-devtools-extension/issues/124).

**Comment by jameskraus** [comment]
Thanks for the pointer @zalmoxisus.
