### ISSUE TITLE
<-- React warning -->

### ISSUE THREAD

**Issue by ghost** [gaearon/redux-devtools#311]
Hi I use react 15.3.1 with redux-devtools to build a universal web app. There's a warning from react says :
```
warning.js?8a56:36Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) v data-reactid="2"><div data-reactid="3"
 (server) v data-reactid="2"><!-- react-empty: 3 -
```
It seems because of the **DevTools.js** doesn't be wrapped, does anyone know how to handle this?

Here's my DevTools.js :
```
import React from 'react';
import { createDevTools } from 'redux-devtools';
import LogMonitor from 'redux-devtools-log-monitor';
import DockMonitor from 'redux-devtools-dock-monitor';

// createDevTools takes a monitor and produces a DevTools component
export default createDevTools(
  // Monitors are individually adjustable with props.
  // Consult their repositories to learn about those props.
  // Here, we put LogMonitor inside a DockMonitor.
  // Note: DockMonitor is visible by default.
  <DockMonitor toggleVisibilityKey="ctrl-H" changePositionKey="ctrl-Q">
    <LogMonitor theme="tomorrow" />
  </DockMonitor>
);
```

**Comment by peter-mouland** [comment]
Is it because the react-dev-tools don't render on the server?

I came across this also and after finding a related issue I was able to come up with this to get it working:

https://github.com/peter-mouland/react-lego/compare/redux...redux-devtools

**Comment by zalmoxisus** [comment]
DevTools should be used under a flag, only on client and only on development.

In case you're using [the extension](https://github.com/zalmoxisus/redux-devtools-extension), you can include it just by checking `typeof window === 'object' && typeof window.devToolsExtension !== 'undefined'`.
