### ISSUE TITLE
Single quote makes timetravelling crash

### ISSUE THREAD

**Issue by sir-marc** [gaearon/redux-devtools#314]
If i have a single quote inside a string like this: `variable = "Hello I'm Marc"`, redux-devtools don't work anymore. The string can be deep inside an object, but the timetravel functionality stops working immediately. Very strange. does anyone have an idea why and how to solve it?
just adding a `\` before does not help.

edit: the application itself works just fine.

**Comment by zalmoxisus** [comment]
Could you please provide a minimal repo or jsfiddle to reproduce it? I just tried to add this string in our [todomvc example](https://github.com/gaearon/redux-devtools/tree/master/examples/todomvc) and don't see any problems with the slider monitor.

**Comment by sir-marc** [comment]
I'm not able to post the repo.
But the error is gone. I don't know why. Issue can be closed, sorry.
