### ISSUE TITLE
Can't exclude DevTools from production build

### ISSUE THREAD

**Issue by ronanlevesque** [gaearon/redux-devtools#316]
I've followed the doc and I can't manage to make this work. I've tested a small test case like this:

```
// configureStore.js

if (process.env.NODE_ENV === 'production') {
  module.exports = require('store/configureStore.prod');
} else {
  module.exports = require('store/configureStore.dev');
}

// configureStore.dev.js

import { createStore, compose, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';

import reducers from 'reducers/reducers';
import DevTools from 'utils/DevTools';

const enhancer = compose(
  applyMiddleware(thunk),
  DevTools.instrument()
);

const store = createStore(
  reducers,
  enhancer
);

export default store;

// App.js

import React from 'react';
import { Provider } from 'react-redux';
import store from 'store/configureStore';
import DevTools from 'utils/DevTools';

const App = () =>
  <Provider store={store}>
    <DevTools />
  </Provider>;

export default App;
```

And I get the following error: Warning: Failed prop type: Required prop `store.subscribe` was not specified in `Provider`.

I've tested `configureStore.dev.js` and it works perfectly fine on its own.

I'm using the following:

- "webpack": "2.1.0-beta.22"
- "react": "^15.1.0"
- "react-redux": "^4.4.5"
- "redux-devtools": "^3.3.1"
- "redux-devtools-dock-monitor": "^1.1.1"
- "redux-devtools-log-monitor": "^1.0.11"

Any idea?

Thanks in advance for your help.

**Comment by zalmoxisus** [comment]
You didn't provide `configureStore.prod.js`.

[The examples](https://github.com/gaearon/redux-devtools/tree/master/examples) would help to see how to do that.

You could also use [the extension](https://github.com/zalmoxisus/redux-devtools-extension), where it would be just:
```js
const store = createStore(reducer, initialState, compose(
    applyMiddleware(thunk),
    process.env.NODE_ENV !== 'production' &&
    window.devToolsExtension ? window.devToolsExtension() : f => f
  ));
```

or in the upcoming API (it will be released next week) it will be:
```js
import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';
const store = createStore(reducer, initialState, composeWithDevTools(applyMiddleware(thunk));
```

**Comment by ronanlevesque** [comment]
Sorry, forgot to mention this doesn't work if I just try to require `configureStore.dev` out of an if/else statement. Also checked the examples, and even though I followed the exact same syntax, I had no chance with that either.

I guess I'll just wait for the upcoming API and use the extension until then.

Thanks!

**Comment by zalmoxisus** [comment]
The new version of Redux DevTools **Extension** just has been released. [See the post](https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83) for details on how to implement that.

**Comment by KristofaJosh** [comment]
This worked for me
