### ISSUE TITLE
Second monitor + multi-screen

### ISSUE THREAD

**Issue by o1dnik** [gaearon/redux-devtools#317]
I can't grasp how exactly redux-devtools work w/o diving into details of the source code. I wonder if others also experience annoying "feature": the window position always resets to some default weird position in between laptop screen and external monitor on page refresh. In addition I can't find how to turn Off a multi-windows mode. Is there even an option like this ?

**Comment by zalmoxisus** [comment]
Could you please elaborate? Are you using Chrome extension? If so, you probably have `widow.devToolsExtension.open` somewhere because it doesn't open any windows itself.

**Comment by zalmoxisus** [comment]
Hey @o1dnik,

There was such issue for Firefox extension, which was solved in `2.8.0`. Feel free to reopen the issue with more details if it still occurs or if I misunderstood the issue.
