### ISSUE TITLE
Printing state tree

### ISSUE THREAD

**Issue by raaone7** [gaearon/redux-devtools#318]
I couldn't find any option to print the state tree , my state tree has gone too big,  would like to review and optimise it.

Sample of my state tree.

![image](https://cloud.githubusercontent.com/assets/10722171/19227824/86179c80-8f0a-11e6-9ab4-e28faa2a74dd.png)

**Comment by raaone7** [comment]
Go to chart > Export button on the redux dev tool doesn't work :(

**Comment by raaone7** [comment]
import React from 'react';

import { createDevTools } from 'redux-devtools';

import LogMonitor from 'redux-devtools-log-monitor';
import ChartMonitor from 'redux-devtools-chart-monitor';
import SliderMonitor from 'redux-slider-monitor';
import DockMonitor from 'redux-devtools-dock-monitor';

const DevTools = createDevTools(
  <DockMonitor toggleVisibilityKey='ctrl-h'
               changePositionKey='ctrl-q'
               changeMonitorKey='ctrl-m'>
    <LogMonitor theme="tomorrow"/>
    <ChartMonitor />
    <SliderMonitor />
  </DockMonitor>    
);

export default DevTools;

**Comment by zalmoxisus** [comment]
As far as you mention the Export button, you're using [the extension](https://github.com/zalmoxisus/redux-devtools-extension). If so, just open a new window monitor (click one of the first buttons on the bottom) and then press `Command` (`Control`) + `P`, so you can print to PDF or whatever.

**Comment by zalmoxisus** [comment]
There's also [a suggestion to export the graph view in a nicer format](https://github.com/zalmoxisus/redux-devtools-extension/issues/157) in case someone is willing to contribute on implementing that.

**Comment by raaone7** [comment]
Yes, thats correct , using the extension. I would love to contribute, but i am an amateur in redux

**Comment by zalmoxisus** [comment]
I've implemented a print button:
![o98dry40pj](https://cloud.githubusercontent.com/assets/7957859/19320414/d76c18b2-90b9-11e6-88db-680ff85448f1.gif)

The pr is [here](https://github.com/zalmoxisus/remotedev-app/pull/22), will publish it soon, not sure it will land in the next version of the extension though.

Regarding https://github.com/zalmoxisus/redux-devtools-extension/issues/157, if you want to give it a try, there's no need to dig into Redux. Just get the state via store.getState and add a transformer to gnuplot or whatever else, then we can add it also in the extension.

**Comment by zalmoxisus** [comment]
Implemented in `redux-devtools-extension@2.8.0`. See [the release notes](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.8.0).

It didn't work as expected when invoked from devpanel (hangs the browser under some circumstances). So, to have this feature, open the extension in a window (one of first buttons from the bottom).

Let me know whether it works for you.

**Comment by raaone7** [comment]
Many thanks for the print button. It works fine for a small state tree. But doesn't work for mine. Mine is a enterprise application, and the print is failing to show the full chart at step 1. 

Please find attached the JSON and PDF for review.

[StateChart_Login_Step1.json.txt](https://github.com/gaearon/redux-devtools/files/529497/StateChart_Login_Step1.json.txt)

[StateChart_Login_Step1.pdf](https://github.com/gaearon/redux-devtools/files/529496/StateChart_Login_Step1.pdf)

**Comment by zalmoxisus** [comment]
Don't know why the svg is stripped. Will dig into it.

If you want to help to experiment with printing styling, just do `npm i && npm start` for [`remotedev-app` ](https://github.com/zalmoxisus/remotedev-app). The styling is [here](https://github.com/zalmoxisus/remotedev-app/blob/master/src/views/index.jade#L28-L48).

**Comment by raaone7** [comment]
Sure. Did the below.

1. removed my node modules
2. removed the redux devtools extension and
3. did npm instal
4. then npm start
*5. strange the print button not appearing in chrome devtools now. (its v
2.8.0.1) I saw print button in 2.8.0 yesterday*


attached my npm shrinkwrap

**Comment by zalmoxisus** [comment]
Hey @raaone7,

I already fixed that issue in https://github.com/zalmoxisus/remotedev-app/commit/5905d1753e5a5756f484094e034133585fb279c3, will publish a new release of the extension by tomorrow. Yes, I removed the button as it didn't work as expected.

Regarding  `remotedev-app` repo, it's a web version and the core lib of the extension. To use it as a standalone web app, you have to use [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools) instead the extension for your store enhancer.

**Comment by zalmoxisus** [comment]
Published in `redux-devtools-extension@2.8.1`. Feel free to reopen the issue if something else goes wrong.

**Comment by raaone7** [comment]
Thanks Again, It has progressed well. 

Couple of issues found :- 
1. Export button is broken, cant export JSON now
2. The pdf of A3 landscape (very decent size) is not fitting correctly. I thought it will resize and fit the screen.  (this is a little complex chart,but not the most complex one, i will try it once the fix is stable)

[state-chart-little-complex.pdf](https://github.com/gaearon/redux-devtools/files/531783/state-chart-little-complex.pdf)
Not able share the JSON, since the export is broken.

**Comment by zalmoxisus** [comment]
Thanks for the details.

Yes, it's not resized and fitting now, which is on purpose to be able to align and change the size to be printed as you want. Though, you're right we could check if it is outside of the visible area and fit it explecitely in this case. Which better to address in a separate issue on [the extension](https://github.com/zalmoxisus/redux-devtools-extension) or [remotedev-app repo](https://github.com/zalmoxisus/remotedev-app). In case you want to submit a PR it should be what we did [here](https://github.com/zalmoxisus/remotedev-app/pull/22/commits/aa2e6eca17474c1c285695e9d676ac176ac5b761#diff-f058d6486dc77a0d28709d34a5498e8dR17), but I guess without changing `scale` and only when `translate` makes it to be outside. 

Regarding the exporting, could you please open a separate issue about this on [the extension repository](https://github.com/zalmoxisus/redux-devtools-extension/issues) so you can track it? It has a limit of the data equal to url length. So, the only solution would be to exclude intermediate states (in case we still want a downloadable link).

**Comment by zalmoxisus** [comment]
@raaone7, I have just published `2.8.2`, where those issues should be fixed. Let me know whether it helps.

**Comment by raaone7** [comment]
Fantastic work @zalmoxisus  Print is working as expected and so does the export.   This will help the broader community for sure.

Do i need to submit any more issues of tracking ? Apologies , i have been lazy in reporting and busy in developing ;) 

[state-chart-complex.zip](https://github.com/gaearon/redux-devtools/files/536117/state-chart-complex.zip)
[state-chart-complex.pdf](https://github.com/gaearon/redux-devtools/files/536118/state-chart-complex.pdf)


On a side note, kindly drop an email with your address. I would like to send you some cookies for your help as a token of thanks.

**Comment by zalmoxisus** [comment]
No probs :) If you have any other suggestions or troubles there, feel free to open issues on [the extension's repo](https://github.com/zalmoxisus/redux-devtools-extension). BTW, your email is private, you can ping me at zalmoxisus at gmail dot com.

**Comment by raaone7** [comment]
Not sure, if its possible to get a Radial Tidy Tree using D3. That will be very helpful, if we have both views. 

http://bl.ocks.org/mbostock/4063550

**Comment by zalmoxisus** [comment]
Yes, it would be amazing indeed. We'll look into it, thanks for pointing out.

**Comment by djdaniels90** [comment]
Ya, my state tree can't render.  Adding about 400 entries right there.  Is there a way to get around this issue?

![image](https://user-images.githubusercontent.com/6787501/33971226-4098545a-e02c-11e7-854c-5bd1085ab33c.png)
