### ISSUE TITLE
Requiring unknown module "ws" error happens on windows 10

### ISSUE THREAD

**Issue by razor1895** [gaearon/redux-devtools#321]
I update my package version to 0.5.1, it only appears on windows 10, and I have to downgrade to 0.5.0

**Comment by zalmoxisus** [comment]
@razor1895, thanks for the report, but it seems you've mixed up the repos, and wanted to file it to [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools). Related to https://github.com/zalmoxisus/remote-redux-devtools/issues/39, which should be fixed on the latest version of React Native (as discussed there). What RN version do you use?

**Comment by razor1895** [comment]
@zalmoxisus thanks for reply, i use 0.36

**Comment by zalmoxisus** [comment]
Hey @razor1895, I just published `remote-redux-devtools@0.5.2` with the updated socketcluster. Could you please give it a try. If the issue still persists, let's continue the discussion in zalmoxisus/remote-redux-devtools#39.
