### ISSUE TITLE
I'm getting all kinds of $jsan messages, with no circular structures anywhere AFAIK

### ISSUE THREAD

**Issue by JobLeonard** [gaearon/redux-devtools#323]
This basically started happening this morning.

The only changes made since before I got this error was extend (typed) array objects with my own metadata fields. That shouldn't trip up Redux, should it?

![image](https://cloud.githubusercontent.com/assets/259840/19933037/6c45fc2e-a112-11e6-9a3a-ce75673a0f81.png)

**Comment by zalmoxisus** [comment]
Yes, you should have circular references there, unless you set a custom value to `serializeState` parameter.

It is how we show the path of circular references. If you want to get the infinite circular object instead, set [`serializeState` parameter](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md) to `false`. For performance reason it is not by default.

**Comment by JobLeonard** [comment]
You were right. The result of a typo (surprising that the app didn't completely crash to begin with).

The moral of the story, children, is that one should never have two variables which differ by only one capitalised letter in the middle.

On the plus side, what a great tool! ;)

**Comment by zalmoxisus** [comment]
@JobLeonard, glad to know that thanks to DevTools you spotted the problem :)

**Comment by JobLeonard** [comment]
Ok, I don't think I should re-open this, but I'm still seeing this after getting rid of the previous bug. But now it's immediately after the first action dispatch, and I know there's no circular reference at that point in time because *I'm returning the previous unmodified state, which is an empty object*.

But let's assume this is still the result of me doing something I shouldn't.

Is it also possible that one sees this if the "never mutate the previous state of the redux store"-rule is violated later down the road? Like, that this messes with the dev-tool and creates false history messages? If so I'll double-check if I accidentally introduced a shallow copy instead of a deep copy somewhere or something.

**Comment by JobLeonard** [comment]
Wait, I'm using `redux-thunk` and [this old issue on its github page](https://github.com/gaearon/redux-thunk/issues/9) suggests that am I composing the devtools with `redux-thunk` in the wrong order. But that information also looks outdated, so now I'm confused what I should be doing.

Basically, is simple set-up of the store wrong?
```
import { createStore, applyMiddleware, compose } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';
import thunk from 'redux-thunk';

// import the root reducer
import loomAppReducer from './reducers/reducers';

export const store = createStore(
	loomAppReducer,
	composeWithDevTools(applyMiddleware(thunk))
);
```

**Comment by zalmoxisus** [comment]
@JobLeonard, no, it's not related to mutating the state.

By default the extension tries to stringify the state with `JSON.stringify`. When it fails (usually when having circular references), it uses `jsan.stringify` which handles circular structures, but to reconstruct them you have to set [`serializeState` parameter](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md) to `false` (otherwise it show only the path for performance reason).

Just to confirm you can expose the store globally (`window.store = store`) and try to do `JSON.stringify(store.liftedStore.getState)`.

**Comment by zalmoxisus** [comment]
The store configuration looks good.

**Comment by JobLeonard** [comment]
> Just to confirm you can expose the store globally (`window.store = store`) and try to do `JSON.stringify(store.liftedStore.getState)`. 

I guess you meant `JSON.stringify(store.liftedStore.getState())`? That produces:
```js
=> VM238:1 Uncaught TypeError: Converting circular structure to JSON(…)
```

Wat. Ok. I must have another circular structure somewhere then. Somehow. I'm going to dive deeper, but I'm *very* confused.

I'm allowed to make shallow copies of parts of the previous state as long as I don't mutate it, right? I've done so for a while and never got these error messages before. Because that's the only other thing I'm doing that I can think of, and if that's not allowed.. well, then I'll have to say goodbye to redux because we have a *lot* of  *very big* typed arrays in our application.

Anyway, thanks for your patience.

(BTW, which actions give me these circularity messages also depends on when I open the devtools; if I refresh with the tools open I see it at a different action than if I open the page, click a bit, then open the devtools. Is this expected behaviour?)

**Comment by zalmoxisus** [comment]
@JobLeonard why do you think it's not allowed? It has nothing to do with Redux architecture. If you want to see circular references in devtools (instead of the simplified path) just enable it as I wrote above:

```diff
import { createStore, applyMiddleware, compose } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';
import thunk from 'redux-thunk';

// import the root reducer
import loomAppReducer from './reducers/reducers';

+const composeEnhancers = composeWithDevTools({
+  serializeState: false
+});

export const store = createStore(
    loomAppReducer,
-    composeWithDevTools(applyMiddleware(thunk))
+    composeEnhancers(applyMiddleware(thunk))
);
```
> BTW, which actions give me these circularity messages also depends on when I open the devtools; if I refresh with the tools open I see it at a different action than if I open the page, click a bit, then open the devtools. Is this expected behaviour?

Yes, different part of the state history is stringified thus the result from jsan is different. Once again if you want the extension to handle circular structure as expected, enable it.

**Comment by zalmoxisus** [comment]
To prevent mutations, you can add [`redux-immutable-state-invariant` middleware](https://github.com/leoasis/redux-immutable-state-invariant), just make sure to remove it from production, though if you have huge states it could fail to execute.

Also, to make things easier take a look at Immutable.js, [`seamless-immutable`](https://github.com/rtfeldman/seamless-immutable) or [`updeep`](https://github.com/substantial/updeep).

**Comment by JobLeonard** [comment]
> why do you think it's not allowed?

I don't, but I was grasping at straws at this point ;-). Thank you for all the linked libraries. Unfortunately, seamless-immutable appears broken right now and updeep relies on freezing objects which hurts performance too much :-/. But I wasn't mutating any state anywhere anyway, so I'm in the clear.

I can't share the repo, unfortunately. It contains or in other ways provides access to in-progress research data. But I managed to find the bug thanks to your help anyway! :)

So it turns out a new cyclic assignment snuck in somewhere after all: `data.filteredData = data`, where the second `data` used to be named something else. Mental note: never use the `replace all` functionality again, do it step by step to be safe...

For other people finding this in the future with similar issues: exposing the store like zalmoxisus suggested, combined with [this little function for detecting cycles](http://stackoverflow.com/a/34909127/3211791) helped me a *lot*:
```js
function isCyclic(obj) {
  var keys = [];
  var stack = [];
  var stackSet = new Set();
  var detected = false;

  function detect(obj, key) {
    if (typeof obj != 'object') { return; }
    
    if (stackSet.has(obj)) { // it's cyclic! Print the object and its locations.
      var oldindex = stack.indexOf(obj);
      var l1 = keys.join('.') + '.' + key;
      var l2 = keys.slice(0, oldindex + 1).join('.');
      console.log('CIRCULAR: ' + l1 + ' = ' + l2 + ' = ' + obj);
      console.log(obj);
      detected = true;
      return;
    }

    keys.push(key);
    stack.push(obj);
    stackSet.add(obj);
    for (var k in obj) { //dive on the object's children
      if (obj.hasOwnProperty(k)) { detect(obj[k], k); }
    }

    keys.pop();
    stack.pop();
    stackSet.delete(obj);
    return;
  }

  detect(obj, 'obj');
  return detected;
}
```
