### ISSUE TITLE
Right click to copy object

### ISSUE THREAD

**Issue by hanford** [gaearon/redux-devtools#324]
It would be really nice in the `Log monitor` if upon right clicking part of the application state to have the option to copy the selected object / children as an object.. thoughts?

**Comment by zalmoxisus** [comment]
Yes, it's something which would be great to have, and was suggested in https://github.com/gaearon/redux-devtools-log-monitor/issues/60 as well. If you want to contribute to the implementation, it should be done in [`react-json-tree`](https://github.com/alexkuz/react-json-tree) as I wrote [there](https://github.com/gaearon/redux-devtools-log-monitor/issues/60).

Closing in favour of that issue as it's not related directly to this repo.
