### ISSUE TITLE
Can't display action type when I set my action type as a Symbol.

### ISSUE THREAD

**Issue by g0ne150** [gaearon/redux-devtools#325]
```javascript
const MY_ACTION_TYPE = Symbol(`MY_ACTION_TYPE`)
```
![image](https://cloud.githubusercontent.com/assets/8351695/20475973/8eac41aa-b009-11e6-90a2-ce29e7e3ea21.png)

**Comment by zalmoxisus** [comment]
If you're using the extension. Add `serializeAction: true` parameter to serialize symbols and other types that are not serialized by `JSON.stringify`:
```js
const store = Redux.createStore(reducer, window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__({
  serializeAction: true
}));
```

**Comment by g0ne150** [comment]
@zalmoxisus thx, appreciate it.

**Comment by CiaranReen** [comment]
Can we close this now?
