### ISSUE TITLE
Make z-index higher than redbox-react

### ISSUE THREAD

**Issue by sontek** [gaearon/redux-devtools#329]
Right now you can't use redbox-react and devtools together because redbox has a much higher z-index:

https://github.com/commissure/redbox-react/blob/cfba6df1ac4a7ecdc50dedd0990be1a2ad4e1dab/src/style.js#L14

Can we bump the index on this project to go above it?

**Comment by zalmoxisus** [comment]
This repo doesn't add any html elements. I guess you want to implement it on [`redux-devtools-dock-monitor`](https://github.com/gaearon/redux-devtools-dock-monitor) or [`redux-devtools-log-monitor`](https://github.com/gaearon/redux-devtools-log-monitor) or any other monitor you're using.

However, `2147483647` is [the maximum value of z-index in most of browsers](http://stackoverflow.com/a/25461690/4218591).

**Comment by sontek** [comment]
Oops, you are right I meant the monitors.  But that is unfortunate that they set it to the max value.   Not being able to use the DevTools makes redbox-react unusable for me.  I'll create an issue for them

**Comment by zalmoxisus** [comment]
A solution would be to [open DevTools in a new window](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#or-open-them-in-a-new-window) or to [use the browser  extension](https://github.com/zalmoxisus/redux-devtools-extension).
