### ISSUE TITLE
Hot reloading with immutable.js data structures

### ISSUE THREAD

**Issue by BrianHanechak** [gaearon/redux-devtools#330]
I'm having the following problem with hot reloading.... I have a fairly complicated application, and some portions of my state use Immutable list objects. Everything works and the plugin display shows me the contents of the lists as if they were arrays. When I try to do hot-reloading using the debug_session=123 (or similar) query string parameter, upon reload, the system replaces the Immutable.List objects with regular arrays, which causes my application to not work properly.

I'm using the Chrome plug-in version. I just updated to version 2.11.1.1 (which is still having this problem.)

**Comment by zalmoxisus** [comment]
You should specify [`deserializeState` method](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md).

**Comment by BrianHanechak** [comment]
Thanks! After adding deserializeState and deserializeActions, this is working well. (Although I am running out of local storage space; I will file a separate issue.)

**Comment by zalmoxisus** [comment]
@BrianHanechak, see [persisting states right from the extension](https://github.com/zalmoxisus/redux-devtools-extension/pull/276).

**Comment by zalmoxisus** [comment]
Redux DevTools Extension got full support for ImmutableJS out of the box, just pass the Immutable library in `serialize` parameter. See [the release notes](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.12.1) for more details.
