### ISSUE TITLE
devTools should have a way to remove stagedActions

### ISSUE THREAD

**Issue by ioss** [gaearon/redux-devtools#34]
One UseCase: After having called jumpToState a user might want to remove all actions following that state.

At the moment this would be pretty complicated for a Monitor. Either modifying stagedActions directly and calling jumpToState again to have recomputeStates run. 
Or store the currently skipped Actions, reset the skipped actions and only skip the actions after the current action and then call sweep and then restore the remembered skipped ones... ;)

Also - not sure -, maybe there should be a recomputeStates action.

**Comment by gaearon** [comment]
I agree! Something like `spliceActions` would be nice.

**Comment by gaearon** [comment]
Seems like we already support this with `RECOMPUTE_STATES` (to be changed to `IMPORT_STATE` soon).
