### ISSUE TITLE
How to reset by my code?

### ISSUE THREAD

**Issue by lewis617** [gaearon/redux-devtools#344]
are there methods to reset & commit & revert?

**Comment by zalmoxisus** [comment]
You can just call `store.liftedStore.dispatch({ type: 'RESET' });`. See [`redux-devtools-instrument`](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L8-L11) for the used lifted action types.

**Comment by lewis617** [comment]
Thank you, that's awesome!
