### ISSUE TITLE
Any support to "blacklist" actions?

### ISSUE THREAD

**Issue by jaredrada** [gaearon/redux-devtools#346]
### Background
I have a heartbeat (HTTP request) that gets sent to the server every 30 seconds. I also have a second heartbeat that checks the last time my EventSource feed last sent a message. So effectively I have two heartbeats going on. It's a real time app and important to know the status of the connection.

### Complaint
My redux devtools are littered w/ "DATAFEED_HEARTBEAT" events. It pollutes the real actions that are pertinent to the application state.

### Question
Is there anyway to "blacklist" some actions from appearing on the devtools list?

### Alternatively
If there is no support, can I make a PR to support this feature? Does anyone envision any issues?

**Comment by zalmoxisus** [comment]
If you're using browser's extension [it's already there](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsblacklist--actionswhitelist). If not, you can include [Filter Actions Compassable Monitor](https://github.com/zalmoxisus/redux-devtools-filter-actions). In both cases the actions are blacklisted while sending data to the monitor, not in Redux DevTools enhancer as it would lead to inconsistent state.
