### ISSUE TITLE
💦 DevTools monitor gone with webpack 2

### ISSUE THREAD

**Issue by phun-ky** [gaearon/redux-devtools#349]
> This is probably a rubber duckie session, but bear with me

After switching to `webpack@2.2`, I found that the DevTools (dock) has gone AWOL. I cannot figure how this has happened. I'm on the end of the workday and stuck in a rut here.

    "webpack": "2.2.0",
    "redux-devtools": "^3.3.2",
    "redux-devtools-dock-monitor": "^1.1.1",
    "redux-devtools-log-monitor": "^1.2.0",

    // inside <Provider><Oidcprovider> in Root.jsx (routes)
    {process.env.NODE_ENV !== 'production' ? require('./DevTools').default : null}

    // configurestore.dev.js
    const store = compose(
      applyMiddleware(thunkMiddleware, oidcMiddleware),
      DevTools.instrument()
    )(createStore)(rootReducer, initialState);

    // DevTools.jsx
    import React from 'react';
    import { createDevTools } from 'redux-devtools';
    import LogMonitor from 'redux-devtools-log-monitor';
    import DockMonitor from 'redux-devtools-dock-monitor';

    export default createDevTools(
      <DockMonitor
        defaultIsVisible={false}
        toggleVisibilityKey='ctrl-d'
        changePositionKey='ctrl-q'>
        <LogMonitor />
      </DockMonitor>
    );

What could possibly have happened?

**Comment by zalmoxisus** [comment]
As I see, it's not visible by default, you should press `ctrl+d` to show it. Try changing `defaultIsVisible` to `false`. Also make sure to render the component imported from './DevTools'.

**Comment by phun-ky** [comment]
@zalmoxisus sorry, I must have given you the impression that I haven't used this before. It's always worked before, and I can't figure out what has happened with it. And as you see from the code supplied, I do render it.

**Comment by phun-ky** [comment]
After doing some digging, it seems to me that, for now, the culprit of this issue is Webpack 2. I've manually retraced steps in the commits for now, checking out every commit until I got it to work. Will update when I know more

**Comment by phun-ky** [comment]
I see that I never hit `DevTools.prototype.render` , but I hit `function createDevTools(children) {`, investigating further

**Comment by phun-ky** [comment]
Yeah, found the culprit. Me. In the haze of using `webpack@2*` I forgot the basics of module importing it seems. Working with this in `DevTools.jsx` makes it work like a charm.

As stated in the issue, this was a rubber duckie session :duck: :duck:  :weary: 

    import React from 'react';

    let devtools = null;

    if(process.env.NODE_ENV !== 'production'){

      const reduxDevTools = require('redux-devtools');
      const LogMonitor = require('redux-devtools-log-monitor').default;
      const DockMonitor = require('redux-devtools-dock-monitor').default;

      devtools =  reduxDevTools.createDevTools(
        <DockMonitor
          defaultIsVisible={false}
          toggleVisibilityKey='ctrl-d'
          changePositionKey='ctrl-q'>
          <LogMonitor />
        </DockMonitor>
      );

    }

    export default devtools;
