### ISSUE TITLE
Display nested state props in ascending order

### ISSUE THREAD

**Issue by malmyros** [gaearon/redux-devtools#361]
We often use redux dev tools to check the application state. Unfortunately the nested key values show in an ordered manner based on the way you store them. It would be good order key values in an ascending order so that we can scan through them faster.

**Comment by zalmoxisus** [comment]
Thanks for the suggestion. [`react-json-tree`](https://github.com/alexkuz/react-json-tree) has a `sortObjectKeys` prop for that purpose, but it should be implemented in the monitors as well. Are you using vanilla redux devtools or chrome extension?

**Comment by malmyros** [comment]
Hi ya, I am using the chrome extension at the moment. I think it would be good to have it in the extension as well it helps find what is in the state faster. Also you when the number of props is greater than 40 you need to expand them which adds an extra click. I could submit another issue if need be.

**Comment by zalmoxisus** [comment]
We cannot sort an object on the extension side. It should be done for every monitor. At the moment only [`redux-devtools-chart-monitor`](https://github.com/romseguy/redux-devtools-chart-monitor) has implemented `isSorted` prop, though it is not as suitable for lots of keys. The most suitable monitor for this case would be [`redux-devtools-filterable-log-monitor`](https://github.com/bvaughn/redux-devtools-filterable-log-monitor/), which has the ability to filter keys and values of objects (as it is shown in the demo). However, it is not included in the extension, we plan to include it in`3.0`, where it will be possible to better manage the monitors.

**Comment by malmyros** [comment]
Right, ok that's not a problem i can start using that then. Thanks a lot for your help.
