### ISSUE TITLE
Styling should be in a separate css styles

### ISSUE THREAD

**Issue by olegstepura** [gaearon/redux-devtools#37]
You several times said that devtools are currently ugly in terms of design.
It would be way much faster fixed if styling of devtools would be ovewritable. When it's inline noone can do anything about it. If styles would be separated to a css file and be combined inside several classNames - it would be easy to anyone overwrite this styles and soon someone can start thinking of a pull request.

**Comment by lapanoid** [comment]
My 50 cents for voting rather for this approach http://www.youtube.com/watch?v=ERB1TJBn32c against css. We can have styles in a different directory using this https://github.com/FormidableLabs/radium f.e.
scss or less are better then css, js is better of them all.

**Comment by gaearon** [comment]
>When it's inline noone can do anything about it.

Yes you can—you can copy `LogMonitor` into another project, and style it in a beautiful way, and share. :-)

Styling is not just CSS—it's also component structure. I'm happy to make it more customizable, but CSS isn't the real solution here. It's easy to build your own monitor that renders differently, and I want people to build more monitors, so we can grab good ideas (and design choices) from them in the official devtools.

**Comment by lapanoid** [comment]
@gaearon of coarse people can do that but for more html and css guys it would be significanly easier to reason about ui apperance if styles were not inline.

**Comment by olegstepura** [comment]
Well, separating the `LogMonitor` isn't an obvious way to  tell the truth. For me it wasn't.
The whole thing about putting styles to code is a misconception IMHO (yes, I watched the video @lapanoid mentioned and I checked out `radium` earlier). And here is why I think inline styles are evil:

* A person who knows CSS  only (markup guy) will not be able to change application style.
* It's not easily overwritable. If a person, who designed a module only did inline styling without allowing to ovewrite it, it's impossible. I tried using `callemall/material-ui` and gave up (4 ex there is no way to put your <Link/> components to a Menu. If you use a `react-router` >=v1.0.0 the is no way to just put your `<Link/>` inside. But when I started using google's MDL, I just added styles to `<Link/>`. That's it.).
I'm sure there will appear hundreds of projects which have inline styling and no ability to ovewrite it. 
* Even if a person adds support to ovewrite inline styles with some styles passed via props or whatever, how do I modilfy props of children elements? There are projects that generate children inside a component with inline styling. Styles of children are just locked.
* Webpack allows to include CSS. This is just great! Just write your styles in CSS and include it inside of a component. This way you have only styles your current component uses and there is no longer dead code problem, etc.
* CSS was invented for styling. Let's face it. We are reinventing the wheel again.
* With webpack we can use not only CSS, but all those cool preprocessors like SASS, LESS, Stylus etc... [CSS-next](http://cssnext.io/) is my favorite. The coolest thing is that we can use all of them in a single project

**Comment by lapanoid** [comment]
@olegstepura 
> A person who knows CSS only (markup guy) will not be able to change application style.

There no significant difference in syntax with css and radium approach.

>CSS was invented for styling. Let's face it. We are reinventing the wheel again.

Dom was invented for web, react is reinvention of the wheel.

> Even if a person adds support to ovewrite inline styles with some styles passed via props or whatever, how do I modilfy props of children elements? There are projects that generate children inside a component with inline styling. Styles of children are just locked.

This complex behavior should be managed by react component, that is the whole point. Styles is a part of behavior, react component knows what to do with its children on some props, so it should manage styles for them as well. 

Inline styles does not mean that you will need to modify styles in react component. All styles should be extracted to other folder where markup guys will be able to change app style. Here I completelly agree with you.

Finally js is much powerfull than css, scss, less. It is programming language not some preprocessor you trully can do with styles whatever you want.

**Comment by olegstepura** [comment]
@lapanoid I'm sure this is not the only one thread where people dispute on this topic. The issue is that this approach leads to such issues appear. It will apear. In almost each project that uses inline styles. Because people may just forget to allow overwriting those styles. And later on mainatiner will add more functionality and will foget to allow overwrite it again. And this story starts again.

Using extranal named styles just eliminates such issues from the very beginning. Developer has nothing to worry about and becomes a happy creator again ;) This is why I think inline styles approach has no future.

**Comment by gaearon** [comment]
Haha. Please let's not derail this thread into another CSS vs inline styles thread. This was not at all what I meant.

What I meant is, LogMonitor is a small React component, and it will take you half an hour to come up with your own version. If we expose pluggable styles for it, we're going to break your appearance on every new release because something slightly changed. What's the point? Copy paste it to your project and start experimenting. There's nothing "official" about it yet, it's too dumb.

**Comment by olegstepura** [comment]
@gaearon  What will we do when `redux-devtools` will be updated and we'll need to update our `LogMonitor`?
Forking (via `npm install`) is better than copying =)

**Comment by gaearon** [comment]
I'm not sure I understand the question. The whole point is that monitors are swappable. The one that ships with devtools is just an example. I don't want people to extend it with CSS or something else—I want them to experiment with custom monitors. Ideally we'll remove `LogMonitor` and move it to a different project when it's mature.

**Comment by lapanoid** [comment]
@gaearon If LogMonitor will be out of core there we should not worry about its styles - true. But it still applies to https://github.com/gaearon/redux-devtools/issues/38.

**Comment by olegstepura** [comment]
Ok, it's clear. Please let the default monitor be there for a quick start. And the intention of hacking on custom monitors may be pointed in a readme ;)

**Comment by gaearon** [comment]
It is in readme, last paragraph :-)

**Comment by gaearon** [comment]
Well, it's not ugly now!
