### ISSUE TITLE
Idea: A monitor to dock monitors

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux-devtools#38]
With https://github.com/calesce/redux-slider-monitor and https://github.com/lapanoid/redux-devtools-gentest-plugin I think it's evident that monitors can do more than one thing.

In fact the current monitor does too many things. It wastes the precious screen estate on JSON state which is hardly readable. What if there was a separate `CurrentStateMonitor` that only displays the current state in full height, with a proper tree view? Then we could change the default monitor to only show the path chosen in the `CurrentStateMonitor`. 

But then you'd need to find an easy way to keep multiple monitors visible. Wouldn't it be cool if there was a "monitor manager" that's also a monitor by itself, but renders a box like

````
 ________________________
| [show actions]        |
| [show current state]  |
| [show test generator] |
| [show slider]         |
| [show custom monitor  ]
_________________________
```

When a button is pressed, it would render those monitor floated left next to it. You can view actions + current state, or actions + test generator, or current state + slider, or any other combination.

API would be like this:

```js
<DevTools store={store}
                    monitor={CompositeMonitor}
                    monitors={{
                       'show actions': LogMonitor,
                       'show current state': CurrentStateMonitor,
                       'show test generator': TestGeneratorMonitor,
                       'show slider': SliderMonitor,
                       'show custom monitor': MyCustomMonitor
                    }} />
```

Of course you are free to only use two, or three, or any count of any monitors you like. The main goal here is to make some official way to mix them and on the other hand make it easy to show/hide individual monitors so they don't waste screen space when you don't need them.

Thoughts? This should be doable in userland right now. The “visible monitors” thing could be kept in `monitorState` by the `CompositeMonitor`.

**Comment by ioss** [comment]
I like that!

But I think the title (text/color/etc) should be the responsibility of the Monitor and not the CM and it should be changeable at runtime, so LogMonitor could show the total/unread count of logentries: "Actionlog (12/3)" in the CM.
Also I don't think `DevTools` need's to know, if the Monitor is a composite or not, so we don't need a prop "monitors".

```javascript
const compositeMonitor = ...
const logMonitorA = new LogMonitor(someconfig); // or LogMonitor.create or createLogMonitor or whatever
const logMonitorB = LogMonitor(someotherconfig);
...

compositeMonitor.addMonitors(logMonitorA, logMonitorB, currentStateMonitor, ....);

// or shorter but still in JS not JSX
const compositeMonitor = composeMonitors(
    createLogMonitor(confA),
    createLogMonitor(confB),
    createCurrentStateMonitor(),
    createTestGeneratorMonitor(),
   ...
);


<DevTools store={store} monitor={compositeMonitor} />
```

**Comment by gaearon** [comment]
DevTools proxies all unknown properties to the monitor, so CompositeMonitor would just receive `monitors` as a prop.

I want to avoid generating a class because this won't place nicely with React Hot Loader. It will replace the class every time you change a reducer and the update bubbles. We'll have a better solution for that later, but that's a different issue.

**Comment by ioss** [comment]
I see.
You meant (non ReactComponent) instances with their own config/state, because Monitor is a (React Component) class. Right? Haven't read (React) Hot Loader yet... probably should :)

But title updates should be doable anyway through state or by providing a prop-update-title-function to the child monitors.
Also, I like the idea of configurability, so I could have two LogMonitors with different filters/select etc.
Not sure how that can be done?

**Comment by lapanoid** [comment]
Pretty raw implementation of this
demo - http://lapanoid.github.io/redux-devtools-monitor-dock/ 
repo - https://github.com/lapanoid/redux-devtools-monitor-dock

**Comment by gaearon** [comment]
@lapanoid 

Wow, I'm so excited!
I hope you can collaborate with @iktl in #41 to figure out some common solution for laying out monitors.

**Comment by lapanoid** [comment]
@gaearon I think I'll implement CurrentStateMonitor as well I had this idea too. It would be great to have monitor for some custom selections as well, pretty easy to do both with one monitor.

**Comment by gaearon** [comment]
I'm closing as there [have been some experiments](http://lapanoid.github.io/redux-devtools-monitor-dock/ ), and I want to have a built-in docking solution as part of #132. It may not support multiple monitors at first, but it will make monitors more easily composable thanks to reducer composition.

**Comment by tnrich** [comment]
Hey @gaearon , is there any update on the "multiple monitor" front? I'd love to be able to use both the filterable monitor and the standard LogMonitor together at the same time.

Thanks!

**Comment by gaearon** [comment]
For now you can use https://github.com/zalmoxisus/redux-devtools-extension which lets you select multiple monitors. I'm not sure if it includes Filterable monitor though. If not you can ask @zalmoxisus to include this.

I haven't done work on making multiple monitors work at the same time but I'm pretty sure it's doable with the v3 API. Feel free to take a stab at it :-)

**Comment by tnrich** [comment]
Hey @gaearon, thanks for the tip to try the chrome extension. 

My ideal solution would be to have the option to include multiple devtools, and then be able to toggle which one you're currently viewing by hitting ctrl-j (or some other command).

I saw you mentioned this: https://github.com/YoruNoHikage/redux-devtools-dispatch/blob/master/src/MultipleMonitors.js

Is the MultipleMonitors component just popping multiple tools into the devtool window? I'll try it out and see what I can do with it.

Thanks!

**Comment by zalmoxisus** [comment]
It wouldn't be possible to include multiple devtools as every one will try to add its `liftedStore` to your `store`, that's why [we're preventing it](https://github.com/gaearon/redux-devtools/blob/master/src/instrument.js#L361-L366).

You can create your container as [we do in the extension](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/containers/App.js), and [use it as a monitor in devtools](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/containers/DevTools.js). You'll also need a second devtools container, which will go to the store configuration, where you will include the filterable monitor in order to update its reducers.

**Comment by gaearon** [comment]
>Is the MultipleMonitors component just popping multiple tools into the devtool window? I'll try it out and see what I can do with it.

It acts like a monitor but delegates rendering and updating to its children monitors. That’s why monitors are composable.

**Comment by gaearon** [comment]
Note that we support switching multiple monitors inside `DockMonitor` now.

![](https://camo.githubusercontent.com/cc9b9701f3984f3b8cfb6264c214217b0451df09/687474703a2f2f692e696d6775722e636f6d2f51624e7a4e57342e676966)

**Comment by tnrich** [comment]
@gaearon so cool! Nice work, I can't wait to try it out!
