### ISSUE TITLE
Default show/hide by cookie/localstorage

### ISSUE THREAD

**Issue by edtoken** [gaearon/redux-devtools#384]
Hello! In our project we added one convenient feature.
default value of show/hide after page refresh by cookie value DevTools:defaultShow

And, developers can enable/disable panel from cookie.
Now, we moved it value to localstorage.

What do you think about this?

**Comment by edtoken** [comment]
I would like implement this, if you think it's good idea)

**Comment by zalmoxisus** [comment]
It should already work out of the box, when you include `persistState` and specify `debug_session` in the url. See [Walkthrough](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md) for more details.
