### ISSUE TITLE
Not an issue but an awesome suggestion

### ISSUE THREAD

**Issue by JiniHendrix** [gaearon/redux-devtools#386]
It would be amazing to be able to type in an action type and payload to simulate dispatches of actions instead of having to build a bunch of other components to test!!!!

**Comment by conor909** [comment]
Cant you do that already if you click the dispatcher button on the bottom?

**Comment by zalmoxisus** [comment]
Yes, as @conor909 mentioned it's available for Chrome extension. For `redux-devtools` you need [`redux-devtools-dispatch` monitor](https://github.com/YoruNoHikage/redux-devtools-dispatch).
