### ISSUE TITLE
Redux DevTools bottom content is covered and cant scroll furthermore.

### ISSUE THREAD

**Issue by adityapurwa** [gaearon/redux-devtools#387]
![reduxfirefox](https://user-images.githubusercontent.com/6219895/32933040-ee6eff0c-cb9b-11e7-91be-d1d4aacfcb14.png)

As above image, you can see the bottom content got covered and can not be seen.

**Comment by benhodgson87** [comment]
+1. Also having this issue in Firefox 57.0 on OS X 10.13. The scrolling goes beyond the bottom of the window, so the last items in the list are never visible. Affects both left and right panes.

**Comment by shawnmclean** [comment]
Experiencing this on FF 57, Windows.

**Comment by camsjams** [comment]
Also on FF 57 and FF 58 on Linux

**Comment by yuchi** [comment]
@gaearon This is actually preventing the plugin to be usable on Firefox… would you mind to have a look at it?

**Comment by jirikomon** [comment]
I would also really appreciate having this bug fixed. It's super annoying when I cannot see latest dispatched actions and long data trees.

**Comment by zalmoxisus** [comment]
Fixed in version `2.15.2` of the extension. It's available on AMO. Sorry about the delay!

**Comment by yuchi** [comment]
I infer AMO means https://addons.mozilla.org/

**Comment by yuchi** [comment]
Anyway, thank you so much @zalmoxisus! An order of magnitude more usable now!

**Comment by camsjams** [comment]
Thanks a bunch, confirmed fix
