### ISSUE TITLE
Idea: "Log" button for states/actions

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux-devtools#42]
No matter how good UI for object treeview can be, I doubt it'll beat the native UI (and REPL!)
What if we just add a tiny "log" button to every state and action in devtools?
Then you can always dump it to the console when you feel like exploring it in detail.

**Comment by lapanoid** [comment]
@gaearon I guess so, and it is much simpler to do=)

**Comment by calesce** [comment]
I mentioned something similar to that idea in the discussion of #39. Copy to clipboard would be very useful to play with state in the console, as well as if you can paste the cumulative state/actions back into devTools (perhaps from a QA tester's debug session).

**Comment by lapanoid** [comment]
@calesce I used ReactZeroClipboard for copy to clipboard here. https://github.com/lapanoid/redux-devtools-gentest-plugin/blob/master/src/components/TestMonitor.js it is damn simple.

**Comment by calesce** [comment]
Very cool! I hadn't seen that. No excuse not to write tests now :smiley:

**Comment by lapanoid** [comment]
@calesce thanks, there is a room for improvement)

**Comment by gaearon** [comment]
Things like "log" button are part of this long-term UI overhaul: #74.
Import/Export for current state is tracked in #118.
