### ISSUE TITLE
Inspiration: Slider UI

### ISSUE THREAD

**Issue by ericelliott** [gaearon/redux-devtools#43]
Check out [Cerebral's](https://github.com/christianalfoni/cerebral) [slider UI](https://www.youtube.com/watch?v=Fo86aiBoomE). Maybe we could adapt it?

=)

**Comment by gaearon** [comment]
There's a slider monitor for DevTools: https://github.com/calesce/redux-slider-monitor
We are likely to include a variation on it as part of the default monitor after a major UI overhaul: #74.

**Comment by ericelliott** [comment]
Yeah, I have seen the slider monitor for DevTools. I like that there's a good ecosystem evolving. =)
