### ISSUE TITLE
Box Shadow still visible after hiding

### ISSUE THREAD

**Issue by adamalbrecht** [gaearon/redux-devtools#53]
In 1.0, if you toggle it closed (using ctrl-h), the box shadow from the DebugPanel component is still visible.

![devtools_toggle](https://cloud.githubusercontent.com/assets/180203/9226395/7ad8cd4e-40dc-11e5-909c-7f1d027b1d51.gif)

**Comment by adamalbrecht** [comment]
Covered in #52

**Comment by gaearon** [comment]
Should be fixed in 1.0.2
