### ISSUE TITLE
Should monitors be able to annotate lifted actions?

### ISSUE THREAD

**Issue by ioss** [gaearon/redux-devtools#60]
This might be to late, as it is a braking change, but I'd like some opinions.

With the addition of timestamps we saw that devtools and it's api had to be changed.

Shouldn't it be possible for monitors to "annotate" lifted actions with arbitrary values/properties (like skipped/timestamp), without the need for a change of devtools, let's say for "collapsed"?

why not have lifted action be something like:
```javascript
{
  actions: the_original_action,
  skipped: false,
  timestamp: 123456,
  collapsingMonitor: {
    collapsed: true
  }
}

or:
stagedActions: [.....],
stagedActionsState: [{skipped: false, timestamp: 12345, newStates: 'xyz'}, .....]
```

And then probably, updateStagedAction(index/liftedaction, newStagedActionState)?

I know, changing skipped on a lifted-property / statedActionState object, will be more complicated, but I think it might be worth to not have to change devtools every time we need new lifted action states.

**Comment by gaearon** [comment]
Yeah, maybe! At this point the API is getting a bit too complicated and I'm thinking maybe there's an easier way to handle all these scenarios. But again, maybe not. Either way, I'm happy to see more discussion on this, and more potential use cases.

**Comment by gaearon** [comment]
Please see #134, I'd rather solve it this way.
