### ISSUE TITLE
redux-devtools cannot require react

### ISSUE THREAD

**Issue by ashtonwar** [gaearon/redux-devtools#63]
`var _react = require('react');` is resolving to an empty module. I believed the solution was to add an alias to my webpack config:

```
  resolve: {
    alias: {
      react: path.join(__dirname, '../../node_modules', 'react'),
    },
    modulesDirectories: ['', 'src', 'node_modules'],
    extensions: ['', '.json', '.js', '.jsx', '.gss'],
  },
```

But the alias seems to royally screw dependency loading for every other module. The only way I've managed to get `redux-devtools` working is by manually resolving all the paths (`var _react = require('../../../../react/react.js');`) inside the `redux-devtools` source (horrible, temporary fix).

**Comment by gaearon** [comment]
Why is it resolving to an empty module? What is that empty module?

**Comment by ashtonwar** [comment]
In redux-devtools - `lib/react/index.js`:
```
console.log(_react, '---', _react2, '---', _react2.default);
var DevTools = _createDevTools2['default'](_react2['default']);
exports.DevTools = DevTools;
```
Yields
```
Object {__esModule: true} "---" Object {__esModule: true} "---" undefined
```
And this stack trace immediately after as `React` is `undefined`:
```
Uncaught TypeError: Cannot read property 'PropTypes' of undefined
createDevTools @ createDevTools.js?a964:24
(anonymous function) @ index.js?6f56:18
(anonymous function) @ bundle.js:2151
__webpack_require__ @ bundle.js:521
fn @ bundle.js:76
(anonymous function) @ router.js?707
b:5(anonymous function) @ VM23325:83
(anonymous function) @ VM23325:84
(anonymous function) @ bundle.js:927
__webpack_require__ @ bundle.js:521
fn @ bundle.js:76
(anonymous function) @ bundle.js:554
__webpack_require__ @ bundle.js:521
(anonymous function) @ bundle.js:544
(anonymous function) @ bundle.js:547
```
`bundle.js:2151`:
```
/***/ },
/* 266 */
/***/ function(module, exports, __webpack_require__) {

	eval("'use strict';\n\nexports.__esModule = true;\n\nfunction _interopRequire(obj) { return obj && obj.__esModule ? obj['default'] : obj; }\n\nfunction _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }\n\nvar _react = __webpack_require__(266);\n\nvar _react2 = _interopRequireDefault(_react);\n\nvar _createDevTools = __webpack_require__(267);\n\nvar _createDevTools2 = _interopRequireDefault(_createDevTools);\n\nconsole.log(_react, '---', _react2, '---', _react2.default);\nvar DevTools = _createDevTools2['default'](_react2['default']);\nexports.DevTools = DevTools;\n\nvar _LogMonitor = __webpack_require__(290);\n\nexports.LogMonitor = _interopRequire(_LogMonitor);\n\nvar _DebugPanel = __webpack_require__(352);\n\nexports.DebugPanel = _interopRequire(_DebugPanel);\n//@ sourceMappingURL=data:application/json;base64,eyJ2ZXJ...joiIn0=");

/***/ },
```
Source that triggers the error:
```
import {DevTools, DebugPanel, LogMonitor} from 'redux-devtools/lib/react';
```

**Comment by gaearon** [comment]
I'm seriously confused now. :-)
Can you post a standalone broken project?

**Comment by gaearon** [comment]
I'm closing until we can reproduce.
This:

>var _react = require('react'); is resolving to an empty module.

sounds like a problem with your dependency configuration, not the DevTools themselves.

**Comment by gaearon** [comment]
Maybe this will help: https://github.com/gaearon/redux-devtools/issues/69#issuecomment-131395443

**Comment by ashtonwar** [comment]
That'd explain why the module looks like it's trying to import itself in the bundle code.. I've not referenced react anywhere inside my webpack config and am yet to implement code splitting though.

**Comment by ashtonwar** [comment]
Confirmed I renamed the directory to `redux-devtools/lib/som_udder_ting_folder_name` and my import to `import {DevTools, DebugPanel, LogMonitor} from 'redux-devtools/lib/som_udder_ting_folder_name';` and it worked perfectly with `var _react = require('react');`

**Comment by oklas** [comment]
Also for future references with same problem. This problem (feature) occurs when module is not resolved by webpack when module is configured as external. https://webpack.github.io/docs/library-and-externals.html This feature is especially for library packages.
