### ISSUE TITLE
Detecting if an action is being replayed

### ISSUE THREAD

**Issue by rt2zz** [gaearon/redux-devtools#71]
There are some cases where a reducer (or middleware) may want to skip handling an action which is being replayed. The main case that comes to mind is that of 'transient' state, state that only makes sense in its contemporary environment.

It would be nice if we could detect if an action is being replayed, thus enabling transient state to play well with devtools.

How to achieve this is tricky and as far as I can see all options are inelegant:
1. Add some meta to the replayed action object.
2. Set a global variable, like `process.env.REDUX_REPLAY = true`
3. Add a `isReplay()` method to the store. Then middleware can call isReplay and act accordingly.

**edit**: updated options, did not realize all actions are objects by the time they hit the reducer.

Thoughts?

**Comment by rt2zz** [comment]
To clarify, I do not expect or think that traditional reducers should be using this, or keeping 'transient' state. However there are some interested possibilities with having middleware / store enhancers that use transient state to track / manage side-effects.

**Comment by gaearon** [comment]
Can you give a more specific example?

**Comment by rt2zz** [comment]
Sure, the specific problem I am working on is basic offline sync. To do this, I need to keep stateful knowledge of the network request, specifically an array of requests that failed and need to be retried at a later time. Since I need to persist this state over long periods of time, and across application restarts, the state needs to be persisted and inspectable.

Redux makes state exceptionally easy to persist, inspect and do other things with in a predictable way (thanks! :smile:), and hence a redux store would be a good place to keep this 'transient' state.

**Comment by rt2zz** [comment]
forgot to mention, how this ties into replay: I want to take these serializable objects representing failed requests from the retry queue, and push them back through the redux dispatcher to be attempted again by some middleware. 

Since many networks requests are not idempotent, it would be problematic to retry such a request that has already suceeded, hence the need to filter out these replayed actions within the middleware.

**Comment by gaearon** [comment]
I'm having a hard time wrapping my head about this but it seems like a fairly uncommon scenario. I'm closing because I'm unlikely to work on this, but please let us know if you find a solution.
