### ISSUE TITLE
Include action creation & reducers information?

### ISSUE THREAD

**Issue by peteruithoven** [gaearon/redux-devtools#72]
Currently the debuggers show the action that was run with the arguments and the resulting state. 
Is someone working on displaying information on how action (creators) triggered other actions, common with for example [Async actions](http://rackt.github.io/redux/docs/advanced/AsyncActions.html)? 
Another thing that might be interesting is showing the reducers that where executed (listening to that certain action).
Displaying what code is executed is one of the interesting aspects of [Cerebral](https://github.com/christianalfoni/cerebral/)'s debugger for example.

**Comment by gaearon** [comment]
All reducers are always executed; that's how Redux works. We do subtly highlight the changed fields. There are currently no plans to implement action creator chaining monitoring, but I agree this indeed would interesting. I'd imagine this to require wrapping `applyMiddleware` with something custom that figures out how actions cause other actions. Let's keep it open for now.

**Comment by gaearon** [comment]
I think I'll close this because it's not currently on the roadmap. Again, this should be possible in a more complex version of DevTools—I just don't think I'm going to do this in this project any time soon.

If you want to work on it let me know and I'll give you some tips.
