### ISSUE TITLE
Click target for arrows too small

### ISSUE THREAD

**Issue by borisyankov** [gaearon/redux-devtools#73]
The area that is clickable for the tree arrow is small and hard to click.
The area around the triangle itself need to be clickable.

Replacing margins with paddings usually does the trick, but in this case padding enlarges the arrow.
A solution is to either wrap the arrow with a clickable div or to redo it in svg, it is simple either ways.

**Comment by chentsulin** [comment]
+1 for hard to click

**Comment by nicinabox** [comment]
I think the whole line is clickable? In any case I have you covered in #52.

**Comment by borisyankov** [comment]
Oh, the line itself is clickable indeed. So is the very triangle.
But not the area around the triangle ;)

**Comment by nicinabox** [comment]
Gotcha. I'll try to swap out some of those margins for padding to help make the targets bigger.

**Comment by gaearon** [comment]
PRs to styles are welcome!

**Comment by gaearon** [comment]
Superseded by https://github.com/gaearon/redux-devtools-log-monitor/issues/2.
Style gurus, please help fix it.
