### ISSUE TITLE
Hook for after reset/rollback

### ISSUE THREAD

**Issue by GarrettHeel** [gaearon/redux-devtools#76]
Hi,

I have certain actions that get dispatched in `componentDidMount` that I want to re-trigger after doing a reset or rollback. What's the easiest way to hook into the devtools to do this?

Thanks!

**Comment by gaearon** [comment]
It's best not to hook into devtools at all. Just do it how you'd normally do if the state of your app changed.

```
componentWillReceiveProps(nextProps) {
  if (nextProps.something !== this.props.something) {
    doSomething();
  }
}
```
