### ISSUE TITLE
Filter actions 

### ISSUE THREAD

**Issue by GarrettHeel** [gaearon/redux-devtools#77]
I have certain actions which are generated very frequently. When the `devTools` middleware is applied, this makes things very slow and clutters the monitors with lots of data.

It would be great if there were a way to specify a filter for an action to be ignored by devtools.

Thanks!

**Comment by gaearon** [comment]
>I have certain actions which are generated very frequently. When the devTools middleware is applied, this makes things very slow and clutters the monitors with lots of data.

The slowness is no longer an issue as of `redux-devtools@2.1.5`: #133.

>It would be great if there were a way to specify a filter for an action to be ignored by devtools.

There is a plan for a more modular UI that would allow this, please track https://github.com/gaearon/redux-devtools/issues/74.

**Comment by GarrettHeel** [comment]
Thanks!

**Comment by tomatau** [comment]
I have this working in a fork right now as I couldn't wait and a dirty dirty hack.

It's using React-0.14-rc and has a terrible label statement to break loops but it works, you can supply an array of regex values that will not be displayed in the logMonitor

```js
          <DevTools
            select={state =>get(state, 'myForm')}
            actionTypeFilters={[/UPDATE_FORM/, /IGNORE/]}
            store={store}
            monitor={LogMonitor}
          />
```

```json
"redux-devtools": "tomatau/redux-devtools",
```

**Comment by Anahkiasen** [comment]
:+1: Would love to see this built-in. We have async actions that save data in the back-end and they clutter the whole devtool

**Comment by luisrudge** [comment]
This would be a great. Specially when working with redux-form, which sends A BUNCH of actions. When I use redux-form with dev tools, it lags pretty hard if I type a little faster.

**Comment by ptim** [comment]
I'm in the same boat: getting overwhelmed by state updates, particularly with redux-forms.. +1 for filtering!

**Comment by gaearon** [comment]
Sorry but +1's don't help anyhow. :wink:
Monitors can already be developed by users.
Feel free to fork the log monitor, add filtering to it, and then propose your changes.

**Comment by gaearon** [comment]
Please use https://github.com/zalmoxisus/redux-devtools-filter-actions.
It can be composed with any monitor.
