### ISSUE TITLE
Slows down with the amount of actions displayed

### ISSUE THREAD

**Issue by whodidthis** [gaearon/redux-devtools#81]
Do a lot of items on `examples/todomvc` or write some forms with a form helper like [redux-form](https://github.com/erikras/redux-form), and redux-devtools starts to slow down. Looking at Chrome profiles a lot of time (90%?) seems to be used on React proptype validation. I wonder if removing those would make sense?

![2015-08-20-232056_1920x1080_scrot](https://cloud.githubusercontent.com/assets/2881655/9394634/2b82ed6c-4792-11e5-99c7-5a3954920ecb.png)

**Comment by gaearon** [comment]
There is a giant room for optimization there but I'm not ready to even attempt it until we [write some tests](https://github.com/gaearon/redux-devtools/issues/9). Until it's optimized, yes, it will be slow.

**Comment by gaearon** [comment]
As a temporary measure, you can "Commit" at any time (in the top bar), and the log will start from there.

**Comment by gaearon** [comment]
There's a PR attempted to fix it: https://github.com/gaearon/redux-devtools/pull/133
Can you please test whether it improves the situation?

**Comment by gaearon** [comment]
Fixed by #133, out in `redux-devtools@2.1.5`.
Wouldn't have happened without tests contributed by @ellbee.

**Comment by tals** [comment]
Still slow for me (running `redux-devtools@2.1.5`).

Tried out https://github.com/erikras/react-redux-universal-hot-example, typed some stuff into the redux-form input, and performance nosedives.

**Comment by gaearon** [comment]
Nice, finally somebody provides a way to reproduce :-).
Can you tell if https://github.com/gaearon/redux-devtools/pull/146 improves things?

**Comment by gaearon** [comment]
Please try Redux DevTools 3.0 Beta 2 and leave feedback.
It includes React 0.14 support: https://github.com/gaearon/redux-devtools/releases/tag/v3.0.0-beta-2

**Comment by NeXTs** [comment]
If someone want to keep using v2 and don't need all list of actions (if you need to track only last actions), just add slice to stagedActions array at `redux-devtools/lib/react/LogMonitor.js`
```
var stagedActions = _props.stagedActions.slice(-25);
```
This won't let browser be polluted by huge amount of tags
