### ISSUE TITLE
Split JSONTree into its own npm package?

### ISSUE THREAD

**Issue by chibicode** [gaearon/redux-devtools#85]
Hi, I'm wondering if `JSONTree` can be its own npm package. I need a JSON viewer for my app, and I thought it'd be nice if I can use this.
https://github.com/gaearon/redux-devtools/blob/master/src/react/JSONTree/index.js

Of course I can just import `redux-devtools/src/react/JSONTree` but it'd be nicer if it's in own npm package. I can make a PR if that's ok.

For now, I think I'm going to use this:
https://github.com/Lapple/react-json-inspector

**Comment by gaearon** [comment]
Please make a PR. We want to split `LogMonitor` itself too: https://github.com/gaearon/redux-devtools/issues/61. Splitting JSONTree is a nice start.

Please make sure to keep [the credits](https://github.com/gaearon/redux-devtools/blob/master/src/react/JSONTree/index.js#L1-L4) somewhere in `package.json` and/or README:

```js
// ES6 + inline style port of JSONViewer https://bitbucket.org/davevedder/react-json-viewer/
// all credits and original code to the author
// Dave Vedder <veddermatic@gmail.com> http://www.eskimospy.com/
// port by Daniele Zannotti http://www.github.com/dzannotti <dzannotti@me.com>
```

**Comment by chibicode** [comment]
@gaearon thanks! Made a pull request: https://github.com/gaearon/redux-devtools/pull/86

**Comment by gaearon** [comment]
Awesome, out in 1.1.2.
