### ISSUE TITLE
Use light versions of themes

### ISSUE THREAD

**Issue by Calvein** [gaearon/redux-devtools#87]
Since the themes are from [Base16], is there a way to use the light theme instead of the dark one ?

[Base16]: http://chriskempson.github.io/base16/#solarized

**Comment by gaearon** [comment]
You can pass a custom object to `theme` prop. I made a [repo with base16 themes called base16-js](http://github.com/gaearon/base16-js) so you can feel free to contribute generated light versions there and depend on it directly. In the next version of Redux DevTools we'll depend on [redux-devtools-themes](https://github.com/gaearon/redux-devtools-themes) which in turn depends on [base16-js](https://github.com/gaearon/base16-js) so anything you contribute there will be available with `theme` string prop.
