### ISSUE TITLE
react-redux 1.0.1 and react 0.14.0-beta3

### ISSUE THREAD

**Issue by janusch** [gaearon/redux-devtools#89]
devtools causes a bunch of warnings:

```Warning: Failed propType: Invalid prop `children` supplied to `Provider`, expected a single ReactElement. Check the render method of `DevToolsWrapper`.```

```With React 0.14 and later versions, you no longer need to wrap <Provider> child into a function.```

```Warning: `require("react").findDOMNode` is deprecated. Please use `require("react-dom").findDOMNode` instead.```

I think the first ones are just adjustments to the 1.0 release of react-redux.

for the last one it would be nice if devtools could have support for both react 0.13 and 0.14, is that doable and desirable?

**Comment by FredyC** [comment]
I think you should report this to [gaearon/react-redux]() repo instead since redux nor redux-devtools have no dependency or requirement on React version.

Either way, I haven't tried 0.14 yet, but I am wondering if react-dom package can be used with 0.13. That would make transition very easy.

**Comment by gaearon** [comment]
>I think you should report this to gaearon/react-redux repo instead since redux nor redux-devtools have no dependency or requirement on React version.

No, this is the right place. We're using `findDOMNode` in `LogMonitor`.
We should really split LogMonitor into a separate project: #61. Then it'll be easier to version it.

>if react-dom package can be used with 0.13. That would make transition very easy.

It can't.

**Comment by janusch** [comment]
Just a short update:
the first two warnings are gone in redux-devtools 2.0; great!

´Warning: `require("react").findDOMNode` is deprecated. Please use `require("react-dom").findDOMNode` instead´ - is still pending.

**Comment by gaearon** [comment]
The last warning will go away when we switch to React 0.14, which will happen when it comes out.

**Comment by eriknyk** [comment]
how can be fixed the warning:
> With React 0.14 and later versions, you no longer need to wrap <Provider> child into a function.

Regards.

**Comment by gaearon** [comment]
@eriknyk 

Change

```js
<Provider>
  {() => <Stuff />}
</Provider>
```

to

```js
<Provider>
  <Stuff />
</Provider>
```

Note that this question is unrelated to this repo.

**Comment by chrisfinch** [comment]
@gaearon googling led me to your solution - thanks as this problem was very irritating!

**Comment by MadLittleMods** [comment]
:+1: was working off previous `redux` code and ran into this

**Comment by mastertinner** [comment]
@gaearon, thanks for your solution!

**Comment by gaearon** [comment]
No problem. We only shipped the old API because we waited for React to support parent-based context. The new API was how we wanted it to be from the day one, and once 0.14 shipped, we switched it.

**Comment by barsukov** [comment]
I just only want to say big thanks to @gaearon. I had this problem, googled, find this, fix, done and only spent 1 minute. Awesome.

**Comment by gaearon** [comment]
Thank you! Glad it helped.
