### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux-devtools#9]
Tests are needed badly. The setup is in place.
Mostly we want to test that `./src/devTools` behaves as expected.

I'm lazy so I'd rather see an implementation of https://github.com/gaearon/redux-devtools/issues/8 first, and use *that* to generate some tests for `devTools` by inspecting devTools with devTools.

![](http://cdn.meme.am/instances2/500x/748650.jpg)

**Comment by gaearon** [comment]
Example of unit test: https://github.com/gaearon/redux-devtools/issues/113#issuecomment-140805518
I really need help writing these because I don't have time.
Please contribute.

**Comment by ellbee** [comment]
I'm currently working on this.

**Comment by gaearon** [comment]
Wow. I'm really thankful. :-)

**Comment by ellbee** [comment]
With the plans to extract the log monitor, is it worth me carrying on and writing tests for the current implementation? If the extraction is going to involve a re-write I guess writing tests for it now is not worth the effort.

**Comment by gaearon** [comment]
@ellbee 

Thank you for your efforts so far.
If you'd like to write tests for it, please do it here: https://github.com/gaearon/redux-devtools-log-monitor

(Assuming React 0.14 as minimal version)

**Comment by ellbee** [comment]
Hey, no worries. I'll carry on over there then! Cheers.

**Comment by gaearon** [comment]
The tests are in master now thanks to @ellbee's work.
