### ISSUE TITLE
Examples not working with version 2.0.0

### ISSUE THREAD

**Issue by khronnuz** [gaearon/redux-devtools#92]
Hi, todomvc and counter examples are not working for me. I am getting:

```
ERROR in /Users/jhonny/dev/redux-devtools/src/createDevTools.js
Module not found: Error: Cannot resolve module 'react-redux/lib/components/createAll' in /Users/jhonny/dev/redux-devtools/src
 @ /Users/jhonny/dev/redux-devtools/src/createDevTools.js 19:40-87
```

**Comment by mariopeixoto** [comment]
Same error here:

ERROR in /Users/mario/Documents/workspace/redux-devtools/src/createDevTools.js
Module not found: Error: Cannot resolve module 'react-redux/lib/components/createAll' in /Users/mario/Documents/workspace/redux-devtools/src
 @ /Users/mario/Documents/workspace/redux-devtools/src/createDevTools.js 19:40-87

ERROR in /Users/mario/Documents/workspace/redux-devtools/src/react/LogMonitorEntry.js
Module not found: Error: Cannot resolve module 'react-json-tree' in /Users/mario/Documents/workspace/redux-devtools/src/react
 @ /Users/mario/Documents/workspace/redux-devtools/src/react/LogMonitorEntry.js 19:21-47

ERROR in /Users/mario/Documents/workspace/redux-devtools/src/react/LogMonitorEntryAction.js
Module not found: Error: Cannot resolve module 'react-json-tree' in /Users/mario/Documents/workspace/redux-devtools/src/react
 @ /Users/mario/Documents/workspace/redux-devtools/src/react/LogMonitorEntryAction.js 21:21-47

**Comment by mariopeixoto** [comment]
Looks like a 'npm install' in the root of the project is needed instead of only in the root of the example.

**Comment by knowbody** [comment]
would be great to mention that in the example docs so ppl are not confused
